import SourceLink from './SourceLink';
import React,{useState} from 'react';
import axios from 'axios';
import {MdCheck,MdClose,MdLink} from 'react-icons/md';
import {URL_API} from '../../repositories/baseAPI';
import {GraphData,GraphNode,date,safeUrl} from './types';

export default function ConnectionReview({entity,graph,onChange,onDocument}:{entity:GraphNode;graph:GraphData;onChange:()=>Promise<void>;onDocument:(id:number)=>void}){
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [active,setActive]=useState<number>(),[evidence,setEvidence]=useState<any[]>([]);
  const edges=graph.edges.filter(e=>e.entityId&&(e.from===entity.id||e.to===entity.id));
  const review=async(id:number,status:string)=>{setBusy(true);setError('');setNotice('');try{await axios.patch(`${URL_API}/api/ai/memory-graph/edge/${id}`,{status});setActive(undefined);setNotice(status==='rejected'?'Relação descartada. Você pode recuperá-la em Revisar conexões → Descartadas.':status==='confirmed'?'Relação confirmada.':'Relação devolvida para revisão.');try{await onChange();}catch{setError('Revisão salva, mas não foi possível atualizar o grafo. Atualize a página.');}}catch{setError('Não foi possível salvar a revisão. Tente novamente.');}finally{setBusy(false);}};
  const inspect=async(id:number)=>{setBusy(true);setError('');setActive(id);setEvidence([]);try{setEvidence((await axios.get(`${URL_API}/api/ai/memory-graph/evidence`,{params:{edgeId:id,limit:50}})).data.evidence||[]);}catch{setError('Não foi possível consultar as evidências.');}finally{setBusy(false);}};
  return <section className="brain-connections"><h3>Relações para revisar <span>{edges.length}</span></h3>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{edges.length===0&&<p className="brain-muted">Nenhuma relação nesta janela do grafo.</p>}{edges.map(edge=>{const other=graph.nodes.find(n=>n.id===(edge.from===entity.id?edge.to:edge.from));return <article key={edge.entityId} className="brain-connection"><strong>{other?.label}</strong><p>{edge.label}</p><small>{edge.status==='confirmed'?'Confirmada por você':'Sugestão · aguarda revisão'}</small><div><button disabled={busy} onClick={()=>void inspect(edge.entityId!)}><MdLink/> Evidências da relação</button><button disabled={busy} aria-label={`${edge.status==='confirmed'?'Reabrir revisão da':'Confirmar'} relação com ${other?.label}`} onClick={()=>void review(edge.entityId!,edge.status==='confirmed'?'candidate':'confirmed')}><MdCheck/>{edge.status==='confirmed'?'Reabrir revisão':'Confirmar'}</button><button disabled={busy} aria-label={`Descartar relação com ${other?.label}`} onClick={()=>void review(edge.entityId!,'rejected')}><MdClose/>Descartar</button></div>{active===edge.entityId&&<div className="brain-connection-evidence">{busy?<p>Consultando fontes…</p>:evidence.length===0?<p>Nenhuma evidência disponível.</p>:evidence.map(item=><article key={item.id}><small>{date(item.occurredAt)}</small><strong>{item.title}</strong><p>{item.excerpt}</p>{item.sourceType==='second_brain'?<button onClick={()=>onDocument(Number(item.sourceId.split(':')[0]))}>Abrir documento</button>:safeUrl(item.sourceUrl)&&<SourceLink url={item.sourceUrl}>Abrir original</SourceLink>}</article>)}</div>}</article>;})}</section>;
}
