import SourceLink from './SourceLink';
import React,{useCallback,useEffect,useMemo,useRef,useState} from 'react';
import axios from 'axios';
import {Link,useHistory,useLocation} from 'react-router-dom';
import {MdAdd,MdSearch,MdDeviceHub,MdDescription,MdFolderOpen,MdKeyboardArrowRight,MdClose,MdRefresh,MdSettings,MdStarBorder,MdStar,MdCloudDownload,MdEdit,MdCheck,MdLink,MdMenu,MdChatBubbleOutline,MdOpenInNew,MdHistory,MdInfoOutline,MdSave,MdArchive,MdFileUpload} from 'react-icons/md';
import {URL_API} from '../../repositories/baseAPI';
import Graph from './Graph';
import Organization from './Organization';
import ReviewQueue from './ReviewQueue';
import ConnectionReview from './ConnectionReview';
import Markdown from './Markdown';
import {colors,date,messageDate,Doc,GraphData,GraphNode,Source,sourceNames,safeUrl} from './types';
import {Container} from './styles';
import './styles.css';

const API=`${URL_API}/api/second-brain`;
const emptyGraph:GraphData={nodes:[],edges:[],total:0,shown:0};
type View='knowledge'|'graph'|'note'|'sources'|'ask'|'review';
type Answer={answer:string;citations:{id:number;title:string;source:string;contentKind:string}[];mode:string};

export default function SecondBrain(){
  const history=useHistory(),location=useLocation();
  const [view,setView]=useState<View>(new URLSearchParams(location.search).get('view')==='graph'?'graph':'knowledge'),[docs,setDocs]=useState<Doc[]>([]),[total,setTotal]=useState(0),[sources,setSources]=useState<Source[]>([]),[graph,setGraph]=useState<GraphData>(emptyGraph);
  const [selected,setSelected]=useState<Doc|null>(null),[entity,setEntity]=useState<GraphNode|null>(null),[evidence,setEvidence]=useState<any[]>([]);
  const [query,setQuery]=useState(''),[source,setSource]=useState(''),[folder,setFolder]=useState(''),[pinned,setPinned]=useState(false),[left,setLeft]=useState(()=>window.innerWidth-(window.innerWidth>900?300:40)>=800),[right,setRight]=useState(()=>window.innerWidth>=1450);
  const [loading,setLoading]=useState(true),[opening,setOpening]=useState(false),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [editing,setEditing]=useState(false),[draft,setDraft]=useState({title:'',content:'',folder:'Notas',tags:''}),[dirty,setDirty]=useState(false),[newNote,setNewNote]=useState(false);
  const [question,setQuestion]=useState(''),[answer,setAnswer]=useState<Answer|null>(null),[local,setLocal]=useState(false),[showCollections,setShowCollections]=useState(true),[onlyConcepts,setOnlyConcepts]=useState(true);
  const [archivedId,setArchivedId]=useState<number|null>(null);
  const importRef=useRef<HTMLInputElement>(null);
  const stop=useRef(false),searchRef=useRef<HTMLInputElement>(null),openSequence=useRef(0),listSequence=useRef(0),graphSequence=useRef(0),mounted=useRef(true);
  useEffect(()=>{const resize=()=>{const width=window.innerWidth-(window.innerWidth>900?300:40);if(width<800)setLeft(false);if(width<1150)setRight(false);};window.addEventListener('resize',resize);return()=>window.removeEventListener('resize',resize);},[]);
  const fail=useCallback((e:any)=>setError(e.response?.data?.message||'Não foi possível concluir. Verifique sua conexão e tente novamente.'),[]);
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;stop.current=true;};},[]);
  const loadDocs=useCallback(async(append=false)=>{const sequence=++listSequence.current;setLoading(true);try{const result=await axios.get(`${API}/documents`,{params:{q:query,source,folder,pinned,offset:append?docs.length:0,limit:60}});if(sequence!==listSequence.current)return;setDocs(current=>append?[...current,...result.data.documents]:result.data.documents);setTotal(result.data.total);}catch(e){if(sequence===listSequence.current)fail(e);}finally{if(sequence===listSequence.current)setLoading(false);}},[query,source,folder,pinned,docs.length,fail]);
  useEffect(()=>{const timer=setTimeout(()=>{void loadDocs();},250);return()=>clearTimeout(timer);/* pagination is explicit */ // eslint-disable-next-line react-hooks/exhaustive-deps
  },[query,source,folder,pinned]);
  const loadGraph=useCallback(async()=>{const sequence=++graphSequence.current;try{const result=await axios.get(`${API}/graph`,{params:{q:query,source,folder}});if(sequence===graphSequence.current&&mounted.current)setGraph(result.data);}catch(e){if(sequence===graphSequence.current)fail(e);throw e;}},[query,source,folder,fail]);
  const refresh=useCallback(async()=>{const results=await Promise.allSettled([axios.get(`${API}/sources`),loadGraph()]);if(results[0].status==='fulfilled')setSources(results[0].value.data.sources);else fail(results[0].reason);if(results[1].status==='rejected')throw results[1].reason;},[loadGraph,fail]);
  useEffect(()=>{axios.get(`${API}/sources`).then(result=>{if(mounted.current)setSources(result.data.sources);}).catch(fail);},[fail]);
  useEffect(()=>{const timer=setTimeout(()=>{void loadGraph().catch(()=>{});},400);return()=>{clearTimeout(timer);++graphSequence.current;};},[loadGraph]);
  useEffect(()=>{const handler=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler);},[dirty]);
  useEffect(()=>{if(!dirty)return;return history.block('Há alterações não salvas. Deseja sair desta nota?');},[dirty,history]);
  useEffect(()=>{if(new URLSearchParams(location.search).get('view')==='review')setView('review');},[location.search]);
  const canLeave=()=>!dirty||window.confirm('Descartar as alterações não salvas desta nota?');
  const openDoc=useCallback(async(id:number)=>{const sequence=++openSequence.current;setOpening(true);setError('');try{const item=(await axios.get(`${API}/documents/${id}`)).data;if(sequence!==openSequence.current)return;setSelected(item);setEntity(null);setRight(window.innerWidth>1400);setView('note');setEditing(false);setDirty(false);setNewNote(false);setDraft({title:item.title,content:item.content||'',folder:item.folder,tags:(item.tags||[]).join(', ')});}catch(e){if(sequence===openSequence.current)fail(e);}finally{if(sequence===openSequence.current)setOpening(false);}},[fail]);
  useEffect(()=>{const id=Number(new URLSearchParams(location.search).get('note'));if(id>0)void openDoc(id);},[location.search,openDoc]);
  const navigate=(id:number)=>{if(id===selected?.id&&dirty){setView('note');return;}if(canLeave())void openDoc(id);};
  const create=(title='Nova ideia')=>{if(!canLeave())return;++openSequence.current;setSelected(null);setEntity(null);setNewNote(true);setEditing(true);setDirty(false);setDraft({title,content:'',folder:'Notas',tags:''});setView('note');};
  const save=async()=>{setBusy('Salvando nota');setError('');try{const payload={...draft,tags:draft.tags.split(',').map(t=>t.trim()).filter(Boolean),version:selected?.version};const result=selected&&!newNote?await axios.put(`${API}/documents/${selected.id}`,payload):await axios.post(`${API}/documents`,payload);setDirty(false);await openDoc(result.data.id);await Promise.all([loadDocs(),refresh()]);setNotice('Nota salva.');}catch(e){fail(e);}finally{setBusy('');}};
  const openWiki=async(title:string)=>{if(!canLeave())return;try{const result=(await axios.get(`${API}/documents`,{params:{q:title,limit:200}})).data;const found=result.documents.find((d:Doc)=>d.title.toLocaleLowerCase()===title.toLocaleLowerCase());if(found)void openDoc(found.id);else create(title);}catch(e){fail(e);}};
  const selectNode=async(node:GraphNode)=>{if(node.type==='collection'){setFolder(node.folder);setSource('');return;}if(node.entityId){if(!canLeave())return;setEntity(node);setRight(true);setEvidence([]);const sequence=++openSequence.current;try{const result=await axios.get(`${URL_API}/api/ai/memory-graph/evidence`,{params:{nodeId:node.entityId,limit:50}});if(sequence===openSequence.current)setEvidence(result.data.evidence||[]);}catch(e){fail(e);}return;}navigate(Number(node.id));};
  const synchronize=async()=>{setBusy('Indexando suas fontes');setError('');stop.current=false;let count=0;try{let more=true;while(more&&!stop.current&&mounted.current){const result=(await axios.post(`${API}/sync`,{limit:100},{timeout:120000})).data;count+=result.indexed;setBusy(`${count} documentos indexados`);more=result.more;if(result.sources.some((s:any)=>s.status==='error')){setError('Algumas fontes não foram indexadas. Consulte o painel Fontes.');break;}}await Promise.all([loadDocs(),refresh()]);setNotice(stop.current?'Indexação pausada. Você pode continuar de onde parou.':`${count} documentos atualizados. Fontes indexadas disponíveis para busca.`);}catch(e){fail(e);}finally{setBusy('');}};
  const analyze=async()=>{setBusy('Ativando organização inteligente');setError('');try{await axios.patch(`${API}/organization`,{enabled:true});setNotice('O robô foi ativado. Acompanhe as leituras e os assuntos na área Conhecimento.');setView('knowledge');}catch(e){fail(e);}finally{setBusy('');}};
  const reviewEntity=async(status:'confirmed'|'rejected'|'candidate')=>{if(!entity?.entityId)return;setBusy('Salvando revisão');setError('');try{await axios.patch(`${URL_API}/api/ai/memory-graph/node/${entity.entityId}`,{status});setEntity(status==='rejected'?null:{...entity,status});await refresh();setNotice(status==='confirmed'?'Conceito confirmado.':status==='rejected'?'Sugestão descartada do grafo.':'Conceito devolvido para revisão.');}catch(e){fail(e);}finally{setBusy('');}};
  const importRemote=async(source:Source,restart=false)=>{setBusy(`Importando ${source.label}`);setError('');stop.current=false;let complete=false,first=true;try{while(!complete&&!stop.current&&mounted.current){const result=(await axios.post(`${API}/import/${source.source}`,{restart:first&&(restart||!!source.remoteCompleted)},{timeout:180000})).data;first=false;complete=result.complete;setBusy(`Importando ${source.label}: ${result.read} mensagens`);if(result.skipped)setNotice(`${result.skipped} chats não puderam ser lidos com a permissão atual.`);}await Promise.all([loadDocs(),refresh()]);setNotice(complete?`Histórico acessível de ${source.label} importado. Consulte a cobertura e eventuais restrições da conta.`:'Importação pausada nesta tela. O worker, se ativo, continua o histórico em segundo plano.');}catch(e){fail(e);}finally{setBusy('');}};
  const hydrate=async()=>{if(!selected)return;setBusy('Lendo mensagem original');try{const result=await axios.post(`${API}/documents/${selected.id}/hydrate`,{},{timeout:60000});setSelected(result.data);await refresh();setNotice('Conteúdo completo disponível para leitura e busca.');}catch(e){fail(e);}finally{setBusy('');}};
  const togglePin=async()=>{if(!selected)return;try{await axios.patch(`${API}/documents/${selected.id}`,{pinned:!selected.pinned});setSelected({...selected,pinned:!selected.pinned});await Promise.all([loadDocs(),refresh()]);}catch(e){fail(e);}};
  const ask=async(e:React.FormEvent)=>{e.preventDefault();setBusy('Consultando sua base');setError('');try{setAnswer((await axios.post(`${API}/ask`,{question},{timeout:120000})).data);}catch(e){fail(e);}finally{setBusy('');}};
  const exportVault=async()=>{setBusy('Preparando exportação');try{const response=await axios.get(`${API}/export`,{responseType:'blob',timeout:120000});const url=URL.createObjectURL(response.data);const a=document.createElement('a');a.href=url;a.download='segundo-cerebro.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Base exportada em Markdown. Extraia o ZIP e abra a pasta no Obsidian.');}catch(e){fail(e);}finally{setBusy('');}};
  const importMarkdown=async(files:FileList|null)=>{if(!files?.length)return;setBusy('Importando notas');setError('');let count=0;try{for(const file of Array.from(files)){if(!/\.(md|markdown)$/i.test(file.name))continue;if(file.size>500000)throw new Error('Arquivo muito grande');const content=await file.text();await axios.post(`${API}/documents`,{title:file.name.replace(/\.(md|markdown)$/i,''),content,folder:'Notas importadas',tags:[]});count++;}await Promise.all([loadDocs(),refresh()]);setNotice(`${count} notas Markdown importadas.`);}catch(e){setError(`Importação interrompida após ${count} notas. Arquivos devem ser Markdown com até 500 KB. As notas já importadas foram preservadas.`);}finally{setBusy('');if(importRef.current)importRef.current.value='';}};
  const archiveNote=async()=>{if(!selected||!canLeave())return;setBusy('Arquivando nota');try{await axios.patch(`${API}/documents/${selected.id}`,{archived:true});setArchivedId(selected.id);setSelected(null);setDirty(false);setEditing(false);setView('graph');setNotice('Nota arquivada. Você pode desfazer esta ação.');await Promise.all([loadDocs(),refresh()]);}catch(e){fail(e);}finally{setBusy('');}};
  const undoArchive=async()=>{if(!archivedId)return;try{await axios.patch(`${API}/documents/${archivedId}`,{archived:false});await openDoc(archivedId);setArchivedId(null);setNotice('Nota restaurada.');await Promise.all([loadDocs(),refresh()]);}catch(e){fail(e);}};
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setView('note');setLeft(true);requestAnimationFrame(()=>searchRef.current?.focus());}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'&&editing){e.preventDefault();if(!busy)void save();}if(e.key==='Escape'){searchRef.current?.blur();}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);});
  const switchView=(next:View)=>{setView(next);};
  const filteredGraph=useMemo(()=>{const concepts=onlyConcepts&&!local&&!source&&!folder&&graph.nodes.some(n=>n.entityId);let nodes=graph.nodes.filter(n=>(!concepts||!!n.entityId)&&(!query||`${n.label} ${n.summary}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()))&&(!source||n.type===source)&&(!folder||n.folder===folder)&&(showCollections||n.type!=='collection'));let ids=new Set(nodes.map(n=>n.id));let edges=graph.edges.filter(e=>ids.has(e.from)&&ids.has(e.to));if(local&&selected){const neighbors=new Set<string|number>([selected.id]);edges.forEach(e=>{if(e.from===selected.id)neighbors.add(e.to);if(e.to===selected.id)neighbors.add(e.from);});nodes=nodes.filter(n=>neighbors.has(n.id));ids=new Set(nodes.map(n=>n.id));edges=edges.filter(e=>ids.has(e.from)&&ids.has(e.to));}return {...graph,nodes,edges};},[graph,query,source,folder,showCollections,onlyConcepts,local,selected]);
  const featured=useMemo(()=>{const degree=new Map<string|number,number>();filteredGraph.edges.forEach(e=>{degree.set(e.from,(degree.get(e.from)||0)+1);degree.set(e.to,(degree.get(e.to)||0)+1);});const candidates=filteredGraph.nodes.filter(n=>n.entityId).sort((a,b)=>(degree.get(b.id)||0)-(degree.get(a.id)||0));const chosen=['project','idea','decision','topic','person','memory'].map(type=>candidates.find(n=>n.type===type)).filter((n):n is GraphNode=>!!n);const ids=new Set(chosen.map(n=>n.id));return [...chosen,...candidates.filter(n=>!ids.has(n.id))].slice(0,7);},[filteredGraph]);
  const indexed=sources.reduce((n,s)=>n+s.indexed,0),available=sources.reduce((n,s)=>n+s.availableCount,0);
  const resetFilter=()=>{setSource('');setFolder('');setPinned(false);setQuery('');};
  const title=view==='review'?'Revisar conexões':view==='graph'?'Grafo de conhecimento':view==='sources'?'Fontes conectadas':view==='ask'?'Conversar com minha base':newNote?draft.title:selected?.title||'Escolha uma nota';

  return <Container className="brain-module" aria-label="Segundo cérebro">
    <header className="brain-module-header"><div className="brain-heading-copy"><span className="brain-heading-symbol" aria-hidden="true"><MdDeviceHub/></span><div><span>CONHECIMENTO PESSOAL</span><h1>Segundo cérebro</h1><p>Suas ideias encontram contexto aqui.</p></div></div><div className="brain-header-actions"><button disabled={!!busy} onClick={()=>void synchronize()}><MdRefresh className={busy?'brain-spin':''}/> Atualizar fontes</button><button className="brain-primary" onClick={()=>create()}><MdAdd/> Nova nota</button></div></header>
    <div className="brain-metrics"><article><span className="brain-metric-icon"><MdDescription/></span><div><strong>{indexed.toLocaleString('pt-BR')}</strong><span>Documentos na biblioteca</span></div></article><article><span className="brain-metric-icon mint"><MdDeviceHub/></span><div><strong>{(graph.conceptsTotal||graph.nodes.filter(n=>n.entityId).length).toLocaleString('pt-BR')}</strong><span>Conceitos identificados</span></div></article><article><span className="brain-metric-icon gold"><MdLink/></span><div><strong>{(graph.connectionsTotal||0).toLocaleString('pt-BR')}</strong><span>Relações encontradas</span></div><button onClick={()=>switchView('review')}>Revisar <MdKeyboardArrowRight/></button></article></div>
    <nav className="brain-navigation" aria-label="Áreas do segundo cérebro">
      <button aria-pressed={view==='knowledge'} className={view==='knowledge'?'active':''} onClick={()=>switchView('knowledge')}><MdFolderOpen/> Conhecimento</button>
      <button aria-pressed={view==='graph'} className={view==='graph'?'active':''} onClick={()=>switchView('graph')}><MdDeviceHub/> Mapa de conhecimento</button>
      <button aria-pressed={view==='note'} className={view==='note'?'active':''} onClick={()=>{switchView('note');setLeft(true);}}><MdDescription/> Biblioteca</button>
      <button aria-pressed={view==='review'} className={view==='review'?'active':''} onClick={()=>switchView('review')}><MdCheck/> Revisar conexões</button>
      <button aria-pressed={view==='ask'} className={view==='ask'?'active':''} aria-label="Conversar com minha base" onClick={()=>switchView('ask')}><MdChatBubbleOutline/> Consultar minha base</button>
      <button aria-pressed={view==='sources'} className={view==='sources'?'active':''} aria-label="Fontes e sincronização" onClick={()=>switchView('sources')}><MdSettings/> Fontes e sincronização</button>
    </nav>
    {(view==='graph'||view==='note')&&<div className="brain-filters"><label className="brain-search"><MdSearch/><input ref={searchRef} aria-label="Buscar em toda a base" placeholder="Buscar ideias, pessoas, projetos ou documentos" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Limpar busca" onClick={()=>setQuery('')}><MdClose/></button>}</label><select aria-label="Filtrar por fonte" value={source} onChange={e=>{setSource(e.target.value);setFolder('');}}><option value="">Todas as fontes</option><option value="note">Minhas notas</option>{sources.map(s=><option key={s.source} value={s.source}>{s.label}</option>)}</select></div>}
    {(error||(!busy&&notice))&&<div className={`brain-message ${error?'error':''}`} role={error?'alert':'status'}><MdInfoOutline/><span>{error||notice}</span>{archivedId&&<button onClick={()=>void undoArchive()}>Desfazer</button>}<button aria-label="Fechar aviso" onClick={()=>{setError('');setNotice('');}}><MdClose/></button></div>}
    {busy&&<div className="brain-progress" role="status"><MdRefresh className="brain-spin"/>{busy}{busy.includes('indexad')||busy==='Indexando suas fontes'||busy.startsWith('Importando')?<button onClick={()=>{stop.current=true;}}>Pausar</button>:null}</div>}
    <div className={`brain-app view-${view} ${left?'':'hide-explorer'} ${right&&(entity||selected)?'':'hide-inspector'}`}>
    <aside className="brain-explorer">
      <header className="brain-vault"><strong>Biblioteca</strong><span>{total.toLocaleString('pt-BR')} documentos</span><button aria-label="Fechar explorador" onClick={()=>setLeft(false)}><MdClose/></button></header>
      <div className="brain-explorer-shortcuts"><button className={!source&&!folder&&!pinned?'active':''} onClick={resetFilter}><MdHistory/> Todas as notas <span>{total}</span></button><button className={pinned?'active':''} onClick={()=>{setPinned(!pinned);setSource('');setFolder('');}}><MdStarBorder/> Favoritos</button></div>
      <div className="brain-section-label">BIBLIOTECA <button title="Nova nota" aria-label="Criar nota" onClick={()=>create()}><MdAdd/></button></div>
      <div className="brain-folders"><button className={source==='note'?'active':''} onClick={()=>{setSource(source==='note'?'':'note');setFolder('');}}><MdKeyboardArrowRight/><MdFolderOpen/><span>Minhas notas</span></button>{sources.map(s=><button key={s.source} className={source===s.source?'active':''} onClick={()=>{setSource(source===s.source?'':s.source);setFolder('');setPinned(false);}}><MdKeyboardArrowRight/><i style={{background:colors[s.source]}}/><span>{s.label}</span><small>{s.indexed}</small></button>)}</div>
      <div className="brain-section-label">{query?'RESULTADOS':folder||sourceNames[source]||'DOCUMENTOS'} <span>{total}</span></div>
      <div className="brain-doc-list" aria-busy={loading}>{docs.map(doc=><button key={doc.id} className={selected?.id===doc.id?'active':''} onClick={()=>{navigate(doc.id);if(window.innerWidth<800)setLeft(false);}}><MdDescription style={{color:colors[doc.source]}}/><span>{doc.source==='microsoft_teams'?<><strong title={doc.excerpt||'Mensagem sem texto disponível'}>{doc.excerpt?.trim()||'Mensagem sem texto disponível'}</strong><small className="brain-conversation-title" title={doc.title}>{doc.title}</small><small>{doc.author||'Autor não informado'} · Teams</small><small>{messageDate(doc.occurredAt)}</small></>:<><strong>{doc.title}</strong><small>{sourceNames[doc.source]} · {date(doc.occurredAt)}</small>{query&&<em>{doc.excerpt}</em>}</>}</span>{doc.pinned&&<MdStar className="brain-pin"/>}</button>)}{loading&&<p className="brain-list-hint">Carregando documentos…</p>}{!loading&&!docs.length&&<p className="brain-list-hint">{query?'Nenhum documento encontrado.':'Nenhum documento nesta coleção.'}</p>}{docs.length<total&&<button className="brain-load-more" disabled={loading} onClick={()=>void loadDocs(true)}>Carregar mais ({total-docs.length})</button>}</div>
      <footer className="brain-vault-footer"><i/>{indexed} documentos de fontes<button title="Abrir fontes" aria-label="Abrir fontes" onClick={()=>switchView('sources')}><MdSettings/></button></footer>
    </aside>

    <main className="brain-workspace">
      {view==='note'&&<header className="brain-toolbar"><button aria-label="Mostrar explorador" onClick={()=>setLeft(!left)}><MdMenu/> Documentos</button><strong>{title}</strong><button aria-label="Alternar painel de referências" onClick={()=>setRight(!right)}><MdLink/> Referências</button></header>}
      {opening&&<div className="brain-message" role="status">Abrindo documento…</div>}

      {view==='graph'&&<section className="brain-graph-page"><div className="brain-graph-heading"><div><span className="brain-eyebrow">VISÃO CONECTADA</span><h2>Mapa de conhecimento</h2><p>Selecione um conceito para explorar suas relações e consultar as evidências.</p></div><button onClick={()=>switchView('review')}><MdCheck/> Revisar conexões</button></div>
        <div className="brain-graph-options"><div><button className={!local?'active':''} onClick={()=>setLocal(false)}>Grafo global</button><button disabled={!selected} className={local?'active':''} onClick={()=>setLocal(true)}>Grafo da nota</button></div><label><input type="checkbox" checked={onlyConcepts} onChange={e=>setOnlyConcepts(e.target.checked)}/> Conceitos</label><label><input type="checkbox" checked={showCollections} disabled={onlyConcepts&&!local&&!source&&!folder&&graph.nodes.some(n=>n.entityId)} onChange={e=>setShowCollections(e.target.checked)}/> Coleções</label><span>{filteredGraph.nodes.length} nós · {filteredGraph.edges.length} conexões</span></div>
        <div className="brain-map-canvas"><aside className="brain-discovery" aria-label="Explorar conhecimentos"><div className="brain-discovery-heading"><span>EM DESTAQUE</span><MdDeviceHub/></div><h3>Por onde começar?</h3><p>Explore os assuntos que conectam a sua memória.</p><div className="brain-discovery-list">{featured.map(node=><button key={node.id} className={entity?.id===node.id?'active':''} onClick={()=>void selectNode(node)}><i style={{background:colors[node.type]||colors.topic}}/><span><strong>{node.label}</strong><small>{sourceNames[node.type]||'Conceito'}</small></span><MdKeyboardArrowRight/></button>)}</div>{!filteredGraph.nodes.some(n=>n.entityId)&&<div className="brain-discovery-empty"><MdDescription/><p>Seus documentos são o ponto de partida. Explore a biblioteca para criar novas conexões.</p></div>}<button className="brain-discovery-more" onClick={()=>{switchView('note');setLeft(true);}}><MdFolderOpen/> Abrir biblioteca <MdKeyboardArrowRight/></button></aside>
        <Graph data={filteredGraph} selected={entity?.id||selected?.id} onOpen={node=>void selectNode(node)} local={local}/></div>
        <div className="brain-graph-legend">{onlyConcepts&&!source&&!folder&&!local&&graph.nodes.some(n=>n.entityId)?<div className="brain-concept-legend">{['person','project','idea','topic','decision','memory'].map(key=><span key={key}><i style={{background:colors[key]}}/>{sourceNames[key]}</span>)}</div>:['note','microsoft_mail','gmail_mail','microsoft_teams','activity','assistant_history'].map(key=><button key={key} onClick={()=>setSource(source===key?'':key)}><i style={{background:colors[key]}}/>{sourceNames[key]}</button>)}<span>Arraste para explorar · role para ampliar</span></div>
        {graph.shown<graph.total&&<p className="brain-limit">{onlyConcepts&&!local&&!source&&!folder&&graph.nodes.some(n=>n.entityId)?`Mostrando ${filteredGraph.nodes.length} de ${graph.conceptsTotal||filteredGraph.nodes.length} conceitos. A fila de revisão inclui todas as relações.`:`Grafo mostra ${graph.shown} de ${graph.total} documentos, além dos conceitos. A busca na biblioteca consulta toda a base.`}</p>}
      </section>}

      {view==='note'&&<section className="brain-note-page">{selected||newNote?<><div className="brain-note-actions"><span><i style={{background:colors[selected?.source||'note']}}/>{sourceNames[selected?.source||'note']} <span> / {selected?.folder||draft.folder}</span></span><div>{selected&&<button title="Favoritar" aria-label="Favoritar nota" onClick={()=>void togglePin()}>{selected.pinned?<MdStar/>:<MdStarBorder/>}</button>}{selected?.source==='note'&&<button title="Arquivar nota" aria-label="Arquivar nota" disabled={!!busy} onClick={()=>void archiveNote()}><MdArchive/></button>}{selected?.source==='note'&&!editing&&<button onClick={()=>setEditing(true)}><MdEdit/> Editar</button>}{editing&&<button className="brain-primary" disabled={!!busy||!draft.title.trim()} onClick={()=>void save()}><MdSave/> Salvar</button>}{selected&&<button title="Copiar link da nota" aria-label="Copiar link da nota" onClick={()=>void navigator.clipboard.writeText(`${window.location.origin}/second-brain?note=${selected.id}`).then(()=>setNotice('Link copiado.')).catch(fail)}><MdLink/></button>}</div></div>
        {editing?<div className="brain-editor"><input className="brain-title-input" aria-label="Título da nota" maxLength={500} value={draft.title} onChange={e=>{setDraft({...draft,title:e.target.value});setDirty(true);}} placeholder="Título da nota"/><div className="brain-edit-meta"><label>Pasta<input maxLength={120} value={draft.folder} onChange={e=>{setDraft({...draft,folder:e.target.value});setDirty(true);}}/></label><label>Tags<input value={draft.tags} onChange={e=>{setDraft({...draft,tags:e.target.value});setDirty(true);}} placeholder="ideias, trabalho"/></label></div><textarea aria-label="Conteúdo Markdown" maxLength={500000} value={draft.content} onChange={e=>{setDraft({...draft,content:e.target.value});setDirty(true);}} placeholder={'Comece uma ideia…\n\nUse [[Nome de outra nota]] para criar conexões.\n# Títulos, **destaques** e listas também são bem-vindos.'}/><div className="brain-editor-footer"><span>Markdown · [[links entre notas]]</span><span>{dirty?'Alterações não salvas':'Pronto para escrever'} · Ctrl+S</span></div></div>:<article className="brain-reading"><h1>{selected?.title}</h1><div className="brain-note-meta"><span>{selected?.source==='microsoft_teams'?messageDate(selected.occurredAt):date(selected?.occurredAt)}</span>{selected?.author&&<span>{selected.author}</span>}{selected?.tags?.map(tag=><span className="brain-tag" key={tag}>#{tag}</span>)}</div>{selected?.contentKind==='preview'&&<div className="brain-callout"><MdInfoOutline/><div><strong>Esta fonte disponibilizou uma prévia</strong><p>A busca e a IA consideram apenas o texto disponível abaixo.</p>{['microsoft_mail','gmail_mail'].includes(selected.source)&&<button disabled={!!busy} onClick={()=>void hydrate()}>Carregar mensagem completa <MdOpenInNew/></button>}</div></div>}<Markdown text={selected?.content||(selected?.source==='microsoft_teams'?'Esta mensagem do Teams foi importada sem texto disponível. Consulte a conversa original para verificar seu conteúdo.':'Este documento ainda não tem conteúdo.')} onLink={title=>void openWiki(title)}/>{safeUrl(selected?.sourceUrl)&&<SourceLink className="brain-source-link" url={selected?.sourceUrl}><MdOpenInNew/> Abrir fonte original</SourceLink>}<div className="brain-note-bottom"><MdLink/><span>{selected?.backlinks?.length||0} referências de entrada · {selected?.links?.length||0} links nesta nota</span></div></article>}</>:<div className="brain-empty"><MdDescription/><h2>Um espaço para pensar.</h2><p>Escolha um documento na biblioteca ou crie uma nota.</p><button className="brain-primary" onClick={()=>create()}><MdAdd/> Criar nota</button></div>}</section>}

      {view==='sources'&&<section className="brain-scroll-page"><span className="brain-eyebrow">O QUE ALIMENTA SEU CONHECIMENTO</span><h1>Fontes conectadas</h1><p className="brain-lead">Uma biblioteca pessoal, com origem e cobertura visíveis.</p><div className="brain-source-summary"><div><strong>{indexed.toLocaleString('pt-BR')}</strong><span>documentos indexados</span></div><div><strong>{available.toLocaleString('pt-BR')}</strong><span>disponíveis nos conectores locais</span></div><button className="brain-primary" disabled={!!busy} onClick={()=>void synchronize()}><MdRefresh/> Indexar fontes</button></div><div className="brain-callout"><MdInfoOutline/><div><strong>Seu conhecimento tem uma origem.</strong><p>O índice inclui todo o histórico disponível no Gaspar, sem corte de data. O alcance das contas depende das permissões e da sincronização dos conectores. E-mails em prévia são identificados; anexos e mensagens não sincronizadas não são considerados lidos.</p></div></div>
        <div className="brain-source-cards">{sources.map(s=><article key={s.source}><span className="brain-source-symbol" style={{color:colors[s.source]}}><MdFolderOpen/></span><div><h3>{s.label}</h3><p>{s.indexed} indexados / {s.availableCount} no espelho local · {s.previews?`${s.previews} prévias`:'conteúdo indexado'}</p><small>{s.error||(!s.available?'Conector ainda não disponível':s.lastSyncAt?`Indexado em ${date(s.lastSyncAt)}`:'Aguardando primeira indexação')}</small></div><span className={`brain-source-state ${s.error?'warning':''}`}>{s.error?'Revisar':!s.available?'Indisponível':s.indexed>=s.availableCount?'Indexado':'Pendente'}</span>{['microsoft_mail','gmail_mail','microsoft_teams'].includes(s.source)&&<div className="brain-remote-control"><small>{s.remoteRead||0} mensagens lidas diretamente{ s.remoteCompleted?' / histórico percorrido':''}</small><button disabled={!!busy} onClick={()=>void importRemote(s)}><MdCloudDownload/>{s.remoteCompleted?'Reconsultar histórico':s.remoteRead?'Continuar importação':'Importar histórico completo'}</button>{!!s.remoteRead&&!s.remoteCompleted&&<button disabled={!!busy} onClick={()=>void importRemote(s,true)}>Reiniciar</button>}</div>}</article>)}</div><div className="brain-source-controls"><input ref={importRef} type="file" accept=".md,.markdown" multiple hidden aria-label="Arquivos Markdown" onChange={e=>void importMarkdown(e.target.files)}/><button disabled={!!busy} onClick={()=>importRef.current?.click()}><MdFileUpload/> Importar notas Markdown</button><button disabled={!!busy} onClick={()=>void analyze()}><MdDeviceHub/> Organizar conhecimento com IA</button><button disabled={!!busy} onClick={()=>void exportVault()}><MdCloudDownload/> Exportar base para Obsidian</button><Link to="/settings"><MdSettings/> Configurar contas e integrações</Link></div></section>}

      {view==='knowledge'&&<Organization key={location.search} onDocument={navigate} onGraphChange={refresh}/>}
      {view==='review'&&<ReviewQueue onDocument={navigate} onChange={refresh}/>}
      {view==='ask'&&<section className="brain-scroll-page brain-ask"><div className="brain-ask-symbol">✧</div><span className="brain-eyebrow">PENSE JUNTO COM SUA MEMÓRIA</span><h1>O que vamos conectar hoje?</h1><p className="brain-lead">Encontre decisões, retome conversas e transforme seu histórico em clareza.</p><form onSubmit={e=>void ask(e)}><textarea aria-label="Pergunta para sua base" value={question} maxLength={2000} onChange={e=>setQuestion(e.target.value)} placeholder="O que decidimos sobre o projeto? Quais conversas sustentam essa decisão?"/><div><span><MdLink/> Respostas acompanhadas de fontes</span><button className="brain-primary" disabled={!!busy||!question.trim()}>Consultar minha base <MdKeyboardArrowRight/></button></div></form>{answer&&<article className="brain-answer"><span className="brain-eyebrow">{answer.mode==='ai'?'SÍNTESE COM EVIDÊNCIAS':'FONTES ENCONTRADAS'}</span><Markdown text={answer.answer} onLink={title=>void openWiki(title)}/><h3>Documentos consultados</h3><div>{answer.citations.map(c=><button key={c.id} onClick={()=>navigate(c.id)}><span>[{c.id}]</span><div><strong>{c.title}</strong><small>{sourceNames[c.source]}{c.contentKind==='preview'?' · prévia':''}</small></div><MdKeyboardArrowRight/></button>)}</div></article>}</section>}
    </main>

    <aside className="brain-inspector"><header><MdLink/><strong>{entity?'Conceito conectado':'Conexões e referências'}</strong><button title="Fechar referências" aria-label="Fechar referências" onClick={()=>setRight(false)}><MdClose/></button></header>{entity?<div className="brain-inspector-body"><span className="brain-eyebrow">{sourceNames[entity.type]||entity.type}</span><h2>{entity.label}</h2><p>{entity.summary}</p>{entity.topicId&&<button onClick={()=>{history.push(`/second-brain?topic=${entity.topicId}`);setView('knowledge');}}>Abrir página de conhecimento</button>}<div className="brain-callout subtle">Relação sugerida a partir das fontes. Revise as evidências antes de tratá-la como fato.</div><ConnectionReview key={entity.id} entity={entity} graph={graph} onChange={refresh} onDocument={navigate}/><div className="brain-review-actions"><span>{entity.status==='confirmed'?'Confirmado por você':'Aguardando sua revisão'}</span><button disabled={!!busy} onClick={()=>void reviewEntity(entity.status==='confirmed'?'candidate':'confirmed')}><MdCheck/>{entity.status==='confirmed'?'Reabrir revisão':'Confirmar conceito'}</button><button disabled={!!busy} onClick={()=>void reviewEntity('rejected')}><MdClose/>Descartar sugestão</button></div><h3>Evidências <span>{evidence.length}</span></h3>{evidence.map(item=><article className="brain-evidence" key={item.id}><small>{sourceNames[item.sourceType]||item.sourceType} · {date(item.occurredAt)}</small><strong>{item.title}</strong><p>{item.excerpt}</p>{item.sourceType==='second_brain'?<button onClick={()=>navigate(Number(item.sourceId.split(':')[0]))}>Abrir documento <MdKeyboardArrowRight/></button>:safeUrl(item.sourceUrl)&&<SourceLink url={item.sourceUrl}>Abrir original <MdOpenInNew/></SourceLink>}</article>)}</div>:selected?<div className="brain-inspector-body"><span className="brain-eyebrow">NOTA ATIVA</span><h2>{selected.title}</h2><button className="brain-local-button" onClick={()=>{setLocal(true);setView('graph');}}><MdDeviceHub/> Ver grafo desta nota</button><h3>Referências de entrada <span>{selected.backlinks?.length||0}</span></h3>{selected.backlinks?.map((link,i)=><button className="brain-reference" key={i} onClick={()=>link.id&&navigate(link.id)}><MdLink/><span>{link.title}</span></button>)}{!selected.backlinks?.length&&<p className="brain-muted">Outras notas que usam [[{selected.title}]] aparecem aqui.</p>}<h3>Links nesta nota <span>{selected.links?.length||0}</span></h3>{selected.links?.map((link,i)=><button className="brain-reference" key={i} onClick={()=>link.id?navigate(link.id):create(link.title)}><MdDescription/><span>{link.title}</span>{!link.id&&<small>criar</small>}</button>)}<h3>Propriedades</h3><dl><dt>Origem</dt><dd>{sourceNames[selected.source]}</dd><dt>Formato</dt><dd>{selected.source==='note'?'Markdown':selected.contentKind==='preview'?'Prévia':'Texto completo'}</dd><dt>Atualizado</dt><dd>{date(selected.updatedAt)}</dd><dt>Versão</dt><dd>{selected.version}</dd></dl></div>:null}</aside>
  </div></Container>;
}
