import React,{useCallback,useEffect,useRef,useState} from 'react';
import axios from 'axios';
import {useLocation} from 'react-router-dom';
import {MdArrowBack,MdCheck,MdClose,MdFolderOpen,MdPause,MdPlayArrow,MdRefresh,MdSearch} from 'react-icons/md';
import {URL_API} from '../../repositories/baseAPI';
import Markdown from './Markdown';
import {date,sourceNames} from './types';

const API=`${URL_API}/api/second-brain`;
type Topic={id:number;title:string;area:string;summary:string;reviewed:boolean;status:string;sources:number;nodeId:number};
type Detail=Omit<Topic,'sources'>&{sources:{readingId:number;documentId:number;title:string;summary:string;source:string;contentKind:string;occurredAt:string;confidence:number}[];connections:{id:number;topicId:number;title:string;area:string;label:string;status:string}[]};
type Job={available:boolean;enabled:boolean;state:string;total:number;completed:number;empty:number;previews:number;calls:number;model:string;heartbeat?:string;heartbeatAge?:number;error?:string;areas:{name:string;topics:number}[]};
const stateNames:Record<string,string>={queued:'Na fila para começar',reading:'Organizando seu conhecimento',watching:'Acompanhando novos conteúdos',paused:'Processamento pausado',error:'Aguardando nova tentativa',unavailable:'Organização ainda indisponível'};

export default function Organization({onDocument,onGraphChange}:{onDocument:(id:number)=>void;onGraphChange:()=>Promise<void>}){
  const [job,setJob]=useState<Job>(),[topics,setTopics]=useState<Topic[]>([]),[area,setArea]=useState(''),[query,setQuery]=useState(''),[offset,setOffset]=useState(0),[discarded,setDiscarded]=useState(false);
  const [topic,setTopic]=useState<Detail|null>(null),[editArea,setEditArea]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[showRobot,setShowRobot]=useState(false);
  const location=useLocation();
  const sequence=useRef(0),detailSequence=useRef(0);
  const load=useCallback(async()=>{const seq=++sequence.current;try{const [a,b]=await Promise.all([axios.get(`${API}/organization`),axios.get(`${API}/topics`,{params:{area,q:query,offset,status:discarded?'rejected':'active'}})]);if(seq===sequence.current){setJob(a.data);setTopics(b.data.topics||[]);setError('');}}catch{if(seq===sequence.current)setError('Não foi possível carregar o conhecimento organizado. Verifique a API.');}finally{if(seq===sequence.current)setLoading(false);}},[area,query,offset,discarded]);
  useEffect(()=>{setLoading(true);const timer=setTimeout(()=>void load(),250),poll=setInterval(()=>void load(),10000);return()=>{clearTimeout(timer);clearInterval(poll);++sequence.current;};},[load]);
  useEffect(()=>{if(job?.completed)void onGraphChange().catch(()=>{});},[job?.completed,onGraphChange]);
  const open=async(id:number)=>{const seq=++detailSequence.current;setBusy(true);setError('');try{const data=(await axios.get(`${API}/topics/${id}`)).data;if(seq===detailSequence.current){setTopic(data);setEditArea(data.area);}}catch{setError('Não foi possível abrir o assunto.');}finally{if(seq===detailSequence.current)setBusy(false);}};
  useEffect(()=>{const id=Number(new URLSearchParams(location.search).get('topic'));if(id>0)void open(id);},[]); // eslint-disable-line react-hooks/exhaustive-deps
  const control=async()=>{setBusy(true);setError('');try{setJob((await axios.patch(`${API}/organization`,{enabled:!job?.enabled})).data);setNotice(job?.enabled?'Pausa solicitada. O lote em andamento termina antes de parar.':'Processamento ativado. O robô continuará mesmo com esta tela fechada.');}catch{setError('Não foi possível alterar o processamento.');}finally{setBusy(false);}};
  const review=async(status:string)=>{if(!topic)return;setBusy(true);try{setTopic((await axios.patch(`${API}/topics/${topic.id}`,{area:editArea,status})).data);setNotice(status==='rejected'?'Assunto descartado. A IA preservará sua decisão.':'Classificação salva. Sua correção terá prioridade sobre a IA.');await load();await onGraphChange();}catch{setError('Não foi possível concluir a revisão. Atualize para conferir o estado salvo.');}finally{setBusy(false);}};
  const relation=async(id:number,status:string)=>{if(!topic)return;setBusy(true);try{await axios.patch(`${URL_API}/api/ai/memory-graph/edge/${id}`,{status});await open(topic.id);await onGraphChange();}catch{setError('Não foi possível concluir a revisão da relação.');}finally{setBusy(false);}};
  const moreSources=async()=>{if(!topic)return;setBusy(true);try{const data=(await axios.get(`${API}/topics/${topic.id}`,{params:{offset:topic.sources.length}})).data;setTopic({...topic,sources:[...topic.sources,...data.sources]});}catch{setError('Não foi possível carregar mais fontes.');}finally{setBusy(false);}};
  const percent=job?.total?Math.min(100,Math.round(1000*(job.completed||0)/job.total)/10):0;
  const stale=job?.enabled&&(!job.heartbeat||(job.heartbeatAge||0)>600);
  return <section className={`brain-organization${topic?' reading-topic':''}`}>
    <button className="brain-mobile-robot" aria-expanded={showRobot} aria-controls="brain-organizer-panel" onClick={()=>setShowRobot(!showRobot)}><span className="brain-status-dot"/><span>{stateNames[job?.state||'paused']}</span><strong>{percent.toLocaleString('pt-BR')}%</strong></button>
    <div id="brain-organizer-panel" className={`brain-organizer-status${showRobot?' mobile-expanded':''}`}><div><span className="brain-eyebrow">LEITURA CONTÍNUA · MEMÓRIA COM EVIDÊNCIAS</span><h2>{stateNames[job?.state||'paused']||'Seu conhecimento organizado'}</h2><p>{job?`${(job.completed||0).toLocaleString('pt-BR')} de ${(job.total||0).toLocaleString('pt-BR')} documentos percorridos · ${percent.toLocaleString('pt-BR')}%`:'Consultando o processamento…'}</p></div><button disabled={busy||!job?.available} onClick={()=>void control()}>{job?.enabled?<MdPause/>:<MdPlayArrow/>}{job?.enabled?'Pausar robô':'Iniciar organização'}</button><progress aria-label="Progresso da organização" max={job?.total||1} value={job?.completed||0}/><small>Leitura em etapas, classificação por contexto e sínteses com fontes. {job?.previews||0} prévias de mensagens · {job?.empty||0} registros sem texto. A análise usa a API de IA configurada.</small>{stale&&<p className="brain-callout">Aguardando o robô de processamento. O progresso aparece quando ele enviar uma atualização.</p>}{job?.state==='error'&&job.error&&<p role="alert">{job.error}</p>}</div>
    {error&&<p role="alert" className="brain-message error">{error}</p>}{notice&&<p role="status" className="brain-message">{notice}<button aria-label="Fechar mensagem de organização" onClick={()=>setNotice('')}><MdClose/></button></p>}
    {topic?<article className="brain-knowledge-detail"><header><button onClick={()=>{++detailSequence.current;setTopic(null);setBusy(false);}}><MdArrowBack/> Todos os assuntos</button><button disabled={busy} onClick={()=>void open(topic.id)}><MdRefresh/> Atualizar síntese</button></header><span className="brain-eyebrow">{topic.area}</span><h1>{topic.title}</h1><div className="brain-topic-review"><label>Área<input aria-label="Área do assunto" value={editArea} maxLength={120} onChange={e=>setEditArea(e.target.value)}/></label><button disabled={busy||!editArea.trim()} onClick={()=>void review('confirmed')}><MdCheck/> Salvar classificação</button><button disabled={busy} onClick={()=>void review(topic.status==='rejected'?'candidate':'rejected')}><MdClose/>{topic.status==='rejected'?'Restaurar assunto':'Descartar assunto'}</button><small>{topic.reviewed?'Revisado por você':'Classificação sugerida por IA'}</small></div>
      {topic.summary?<Markdown text={topic.summary.replace(/\[(\d+)\]/g,'[Fonte $1](/second-brain?note=$1)')} onLink={()=>{}}/>:<p className="brain-callout">As fontes deste assunto já foram identificadas. A síntese está na fila de consolidação.</p>}
      <h2>Conexões explicadas</h2>{!topic.connections.length&&<p className="brain-muted">Nenhuma relação sustentada por evidências foi identificada até agora.</p>}<div className="brain-topic-connections">{topic.connections.map(edge=><article key={edge.id}><button className="brain-topic-link" onClick={()=>void open(edge.topicId)}>{edge.area} · {edge.title}</button><p>{edge.label}</p><small>{edge.status==='confirmed'?'Confirmada por você':'Hipótese da IA · confira as fontes'}</small><div>{edge.status!=='confirmed'&&<button disabled={busy} onClick={()=>void relation(edge.id,'confirmed')}>Confirmar relação</button>}<button disabled={busy} onClick={()=>void relation(edge.id,'rejected')}>Descartar relação</button></div></article>)}</div>
      <h2>Fontes e linha do tempo</h2><p className="brain-muted">Cada leitura abaixo abre o documento original. Os números na síntese também levam às fontes.</p><div className="brain-topic-sources">{topic.sources.map(source=><article key={source.readingId}><small>{date(source.occurredAt)} · {sourceNames[source.source]}{source.contentKind==='preview'?' · Apenas prévia':''}</small><button onClick={()=>onDocument(source.documentId)}>{source.title}</button><p>{source.summary}</p><small>Fonte {source.documentId} · Confiança da classificação: {Math.round(source.confidence*100)}%</small></article>)}</div>{topic.sources.length>0&&topic.sources.length%40===0&&<button disabled={busy} onClick={()=>void moreSources()}>Carregar mais fontes</button>}
    </article>:<><div className="brain-knowledge-heading"><div><span className="brain-eyebrow">UM LUGAR PARA CADA CONTEXTO</span><h2>Seu conhecimento, organizado</h2><p>Áreas e assuntos descobertos nas suas fontes. Abra uma página para entender o contexto, as decisões e as conexões.</p></div><label className="brain-search"><MdSearch/><input aria-label="Buscar assuntos organizados" placeholder="Encontrar um assunto…" value={query} onChange={e=>{setQuery(e.target.value);setOffset(0);}}/></label></div><div className="brain-area-tabs"><button aria-pressed={discarded} className={discarded?'active':''} onClick={()=>{setDiscarded(!discarded);setOffset(0);setArea('');}}>{discarded?'Ver assuntos ativos':'Assuntos descartados'}</button><button className={!area?'active':''} onClick={()=>{setArea('');setOffset(0);}}>Todas as áreas</button>{job?.areas?.map(a=><button key={a.name} className={area===a.name?'active':''} onClick={()=>{setArea(a.name);setOffset(0);}}><MdFolderOpen/>{a.name}<span>{a.topics}</span></button>)}</div>
      {loading?<p role="status">Carregando assuntos…</p>:topics.length?<div className="brain-topic-grid">{topics.map(t=><button className="brain-topic-card" key={t.id} onClick={()=>void open(t.id)}><span className="brain-eyebrow">{t.area}</span><h3>{t.title}</h3><p>{t.summary?t.summary.replace(/[#*\[\]]/g,'').slice(0,220):'Fontes identificadas. Preparando a síntese deste assunto.'}</p><footer><span>{t.sources} documentos de apoio</span><span>{t.reviewed?'Revisado':'Sugestão da IA'}</span></footer></button>)}</div>:<div className="brain-knowledge-empty"><MdFolderOpen/><h3>{area||query?'Nenhum assunto neste filtro':'Sua base está pronta para ganhar organização'}</h3><p>{area||query?'Escolha outra área ou ajuste a busca.':'Ative o robô para transformar as fontes em páginas de conhecimento. As áreas aparecerão conforme o modelo encontrar evidências.'}</p></div>}
      <div className="brain-review-pagination"><button disabled={offset===0||loading} onClick={()=>setOffset(Math.max(0,offset-40))}>Anterior</button><span>Página {1+offset/40}</span><button disabled={topics.length<40||loading} onClick={()=>setOffset(offset+40)}>Próxima</button></div></>}
  </section>;
}
