import SourceLink from './SourceLink';
import React,{useCallback,useEffect,useRef,useState} from 'react';
import axios from 'axios';
import {URL_API} from '../../repositories/baseAPI';
import {date,safeUrl} from './types';

type Connection={id:number;label:string;fromLabel:string;toLabel:string;status:string;createdAt:string};
export default function ReviewQueue({onDocument,onChange}:{onDocument:(id:number)=>void;onChange:()=>Promise<void>}){
  const [status,setStatus]=useState('candidate'),[offset,setOffset]=useState(0),[total,setTotal]=useState(0);
  const [rows,setRows]=useState<Connection[]>([]),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const [notice,setNotice]=useState('');
  const sequence=useRef(0);
  const [active,setActive]=useState<number>(),[evidence,setEvidence]=useState<any[]>([]);
  const load=useCallback(async()=>{const request=++sequence.current;setLoading(true);setError('');try{const data=(await axios.get(`${URL_API}/api/second-brain/connections`,{params:{status,offset,limit:25}})).data;if(request!==sequence.current)return;setRows(data.connections);setTotal(data.total);}catch{if(request===sequence.current)setError('Não foi possível carregar a fila de revisão.');}finally{if(request===sequence.current)setLoading(false);}},[status,offset]);
  useEffect(()=>{void load();return()=>{++sequence.current;};},[load]);
  const inspect=async(id:number)=>{setActive(id);setEvidence([]);setBusy(true);setError('');try{setEvidence((await axios.get(`${URL_API}/api/ai/memory-graph/evidence`,{params:{edgeId:id,limit:50}})).data.evidence||[]);}catch{setError('Não foi possível consultar as evidências.');}finally{setBusy(false);}};
  const review=async(id:number,next:string)=>{setBusy(true);setError('');setNotice('');try{await axios.patch(`${URL_API}/api/ai/memory-graph/edge/${id}`,{status:next});++sequence.current;setRows(current=>current.filter(row=>row.id!==id));setTotal(current=>Math.max(0,current-1));setActive(undefined);setNotice(next==='rejected'?'Relação descartada. Ela está na aba Descartadas.':next==='confirmed'?'Relação confirmada. Ela está na aba Confirmadas.':'Relação devolvida para Pendentes.');await load();try{await onChange();}catch{setError('Revisão salva, mas não foi possível atualizar o mapa.');}}catch{setError('Não foi possível salvar a revisão.');}finally{setBusy(false);}};
  return <section className="brain-scroll-page brain-review-queue"><span className="brain-eyebrow">VOCÊ DECIDE O QUE FAZ SENTIDO</span><h1>Revisar conexões</h1><p className="brain-lead">Sugestões extraídas das suas fontes. Confira o contexto antes de confirmar. As mais recentes aparecem primeiro.</p><div className="brain-review-filters">{[['candidate','Pendentes'],['confirmed','Confirmadas'],['rejected','Descartadas']].map(([value,label])=><button key={value} className={status===value?'active':''} disabled={busy||loading} onClick={()=>{setStatus(value);setOffset(0);setActive(undefined);}}>{label}</button>)}<span>{total} conexões</span><button disabled={busy||loading} onClick={()=>void load()}>Atualizar lista</button></div>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{loading?<p role="status">Carregando sugestões…</p>:rows.length===0?<p>Nenhuma conexão nesta página.</p>:rows.map(row=><article className="brain-review-card" key={row.id}><small>{date(row.createdAt)} · {status==='candidate'?'Sugestão ainda não confirmada':status==='confirmed'?'Confirmada por você':'Descartada'}</small><h2>{row.fromLabel}</h2><p className="brain-relation-label">{row.label}</p><h3>{row.toLabel}</h3><div className="brain-review-actions"><button disabled={busy} onClick={()=>void inspect(row.id)}>Ver evidências</button>{status!=='confirmed'&&<button disabled={busy} onClick={()=>void review(row.id,'confirmed')}>Confirmar relação</button>}{status!=='rejected'&&<button disabled={busy} onClick={()=>void review(row.id,'rejected')}>Descartar relação</button>}{status!=='candidate'&&<button disabled={busy} onClick={()=>void review(row.id,'candidate')}>Voltar para pendentes</button>}</div>{active===row.id&&<div className="brain-review-evidence">{busy?<p>Consultando fontes…</p>:evidence.length===0?<p>Nenhuma evidência disponível.</p>:evidence.map(item=><article key={item.id}><small>{date(item.occurredAt)}</small><strong>{item.title}</strong><p>{item.excerpt}</p>{item.sourceType==='second_brain'?<button onClick={()=>onDocument(Number(item.sourceId.split(':')[0]))}>Abrir documento completo</button>:safeUrl(item.sourceUrl)&&<SourceLink url={item.sourceUrl}>Abrir original</SourceLink>}</article>)}</div>}</article>)}<div className="brain-review-pagination"><button disabled={busy||loading||offset===0} onClick={()=>setOffset(Math.max(0,offset-25))}>Anterior</button><span>{total?Math.floor(offset/25)+1:0} / {Math.ceil(total/25)}</span><button disabled={busy||loading||offset+25>=total} onClick={()=>setOffset(offset+25)}>Próxima</button></div></section>;
}
