import React,{useCallback,useEffect,useState}from'react';
import axios from'axios';
import Editor from'react-simple-code-editor';
import Prism from'prismjs';
import'prismjs/components/prism-python';
import{MdAdd,MdEmail,MdHistory,MdPlayArrow,MdRefresh,MdSettings}from'react-icons/md';
import{URL_API}from'../../repositories/baseAPI';
import{Container}from'./styles';
interface Job{name:string;enabled:boolean;description?:string;last_status?:number;last_run_date?:number;last_run_duration?:number;can_run:boolean;is_running?:boolean;start_execution_date?:string;stop_execution_date?:string}
interface History{step_name:string;run_status:number;run_date:number;message:string}
const state=(v?:number)=>v===1?'Sucesso':v===0?'Falhou':v===4?'Em andamento':'Sem execução';
const running=(j:Job)=>Boolean(j.is_running||(j.start_execution_date&&!j.stop_execution_date));
const blank={name:'',description:'',apiDir:'C:\\Dev\\Gaspar Solutions\\GasparAPI',pythonCode:'',enabled:true,schedule:{enabled:true,frequency:'daily',time:'00:00',weekdays:127}};
export default function Settings(){
 const[jobs,setJobs]=useState<Job[]>([]),[job,setJob]=useState<Job|null>(null),[history,setHistory]=useState<History[]>([]),[form,setForm]=useState<any>(blank),[edit,setEdit]=useState(false),[message,setMessage]=useState(''),[togglingJob,setTogglingJob]=useState<string|null>(null);
 const load=useCallback(async()=>{try{const next:Job[]=(await axios.get(`${URL_API}/automations`)).data;setJobs(next);return next}catch{setMessage('Não foi possível carregar as automações.');return[]}},[]);
 useEffect(()=>{load();const timer=window.setInterval(load,5000);return()=>window.clearInterval(timer)},[load]);
 const select=async(j:Job)=>{setJob(j);setEdit(false);setHistory((await axios.get(`${URL_API}/automations/${encodeURIComponent(j.name)}/history`)).data)};
 const open=async(j?:Job)=>{if(!j){setJob(null);setForm(blank);setEdit(true);return}try{setForm((await axios.get(`${URL_API}/automations/${encodeURIComponent(j.name)}/definition`)).data);setEdit(true)}catch(e:any){setMessage(e.response?.data?.message||'Este job não pode ser editado por esta tela.')}};
 const save=async()=>{try{const{name,...body}=form;const r=job?await axios.put(`${URL_API}/automations/${encodeURIComponent(job.name)}/definition`,body):await axios.post(`${URL_API}/automations`,form);setMessage(r.data.message);setEdit(false);load()}catch(e:any){setMessage(e.response?.data?.message||'Não foi possível salvar o job.')}};
 const toggle=async()=>{if(!job||togglingJob)return;const selected=job,enabled=!selected.enabled;setTogglingJob(selected.name);setMessage('');try{const r=await axios.patch(`${URL_API}/automations/${encodeURIComponent(selected.name)}/status`,{enabled});const next=await load();setJob(next.find(item=>item.name===selected.name)||{...selected,enabled});setMessage(r.data.message)}catch(e:any){setMessage(e.response?.data?.message||'Não foi possível alterar o estado do job.')}finally{setTogglingJob(null)}};
 const installDaily=async()=>{try{const apiDir=URL_API.includes('fernandogaspar')?'C:\\API\\Gastos':blank.apiDir;const jobCode=(id:number)=>`import subprocess\nsubprocess.run([r'C:\\Program Files\\Python312\\python.exe','-c',"import sys;sys.path.insert(0,r'C:\\\\API\\\\Gastos');from Modelo.daily_finance_email import run;run(${id})"],check=True)\n`;for(const definition of[{name:'Resumo financeiro diário - Fernando',description:'Resumo diário responsivo do usuário 1 por e-mail.',pythonCode:jobCode(1),enabled:true,schedule:{enabled:true,frequency:'daily',time:'07:30',weekdays:127},apiDir},{name:'Resumo financeiro diário - Cíntia',description:'Resumo diário responsivo do usuário 2 por e-mail.',pythonCode:jobCode(2),enabled:true,schedule:{enabled:true,frequency:'daily',time:'07:40',weekdays:127},apiDir}])await axios.post(`${URL_API}/automations`,definition);setMessage('Resumos financeiros instalados com sucesso.');await load()}catch(e:any){setMessage(e.response?.data?.message||'Não foi possível instalar os resumos financeiros.')}};
 const toggleLoading=job&&togglingJob===job.name;
 return <Container><header><div><span><MdSettings/> CONFIGURAÇÕES</span><h1>Automações</h1><p>Crie rotinas Python, altere agendas e acompanhe suas execuções.</p></div><div className="header-actions"><button className="run" onClick={installDaily}><MdEmail/> Instalar resumos diários</button><button onClick={()=>open()}><MdAdd/> Novo job</button><button onClick={load}><MdRefresh/> Atualizar</button></div></header>{message&&<div className="notice">{message}</div>}<main>
 <section className="job-list"><div className="section-title"><h2>Rotinas</h2></div>{jobs.map(j=><button className={`job ${job?.name===j.name?'selected':''} ${running(j)?'running':''}`} key={j.name} onClick={()=>select(j)}>{running(j)?<span className="job-spinner" aria-label="Executando"/>:<span className={`dot ${state(j.last_status).replaceAll(' ','-')}`}/>}<div><strong>{j.name}</strong><small>{j.description||'Rotina automática'}</small></div><em>{running(j)?'Executando…':state(j.last_status)}</em></button>)}</section>
 <section className="details">{edit?<div className="editor"><h2>{job?`Editar ${job.name}`:'Novo job'}</h2><label>Nome<input disabled={!!job} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Descrição<input value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Pasta da API<input value={form.apiDir||''} onChange={e=>setForm({...form,apiDir:e.target.value})}/></label><div className="schedule"><label>Frequência<select value={form.schedule.frequency} onChange={e=>setForm({...form,schedule:{...form.schedule,frequency:e.target.value}})}><option value="daily">Diariamente</option><option value="weekly">Semanalmente</option></select></label><label>Horário<input type="time" value={form.schedule.time} onChange={e=>setForm({...form,schedule:{...form.schedule,time:e.target.value}})}/></label></div><label>Código Python<Editor value={form.pythonCode} onValueChange={pythonCode=>setForm({...form,pythonCode})} highlight={code=>Prism.highlight(code,Prism.languages.python,'python')} padding={14} textareaId="python-editor" className="python-editor" style={{fontFamily:'Consolas, monospace',fontSize:13,minHeight:360}}/></label><div className="editor-actions"><button onClick={()=>setEdit(false)}>Cancelar</button><button className="run" onClick={save}>Salvar job</button></div></div>:job?<><div className="detail-head"><div><span>DETALHES DA AUTOMAÇÃO</span><h2>{job.name}</h2><p>{job.description||'Sem descrição cadastrada.'}</p></div><div className="header-actions"><button className="toggle-job" disabled={!!toggleLoading} onClick={toggle}>{toggleLoading&&<span className="button-spinner" aria-label="Carregando"/>}{toggleLoading?(job.enabled?'Desativando…':'Ativando…'):(job.enabled?'Desativar':'Ativar')}</button><button onClick={()=>open(job)}>Editar</button>{job.can_run&&<button className="run" onClick={()=>axios.post(`${URL_API}/automations/${encodeURIComponent(job.name)}/start`).then(r=>setMessage(r.data.message))}><MdPlayArrow/> Executar agora</button>}</div></div><div className="meta"><div><small>Status</small><b>{running(job)?'Executando…':job.enabled?state(job.last_status):'Desativado'}</b></div><div><small>Última execução</small><b>{job.last_run_date||'—'}</b></div><div><small>Duração</small><b>{job.last_run_duration||'—'}</b></div></div><h3><MdHistory/> Histórico</h3><div className="history">{history.map((h,i)=><article key={i}><b>{state(h.run_status)}</b><span>{h.step_name} · {h.run_date}</span><p>{h.message}</p></article>)}</div></>:<div className="empty"><MdSettings/><h2>Selecione uma automação</h2></div>}</section>
 </main></Container>
}
