import styled,{keyframes} from 'styled-components';
const appear=keyframes`from{opacity:0;transform:translateY(6px)}to{opacity:1;transform:none}`;
export const Container=styled.div`
min-width:0;padding:20px;border:1px solid rgba(148,163,184,.14);border-radius:14px;color:${p=>p.theme.colors.white};background:linear-gradient(145deg,${p=>p.theme.colors.secondary},${p=>p.theme.colors.tertiary});animation:${appear} .3s ease-out;
.pie-header{display:flex;align-items:flex-start;justify-content:space-between;gap:14px;margin-bottom:15px}.pie-header>div>span{color:#75aaff;font-size:9px;font-weight:800;letter-spacing:.13em}.pie-header h3{margin:4px 0 3px;font-size:18px;letter-spacing:-.025em}.pie-header p{color:${p=>p.theme.colors.gray};font-size:10px}.pie-header button{display:flex;align-items:center;gap:5px;padding:7px 9px;border:1px solid rgba(117,170,255,.3);border-radius:8px;color:#8fc4ff;background:rgba(57,120,245,.08);font-size:10px;font-weight:700;cursor:pointer}
.pie-content{display:grid;grid-template-columns:minmax(190px,.85fr) minmax(210px,1.15fr);align-items:center;gap:18px}.chart-wrap{position:relative;width:100%;height:245px;min-width:0}.pie-cell{cursor:pointer;outline:none;transition:opacity .2s ease,filter .2s ease}.pie-cell:hover{filter:brightness(1.14);opacity:.9}.pie-center{position:absolute;top:50%;left:50%;display:flex;align-items:center;flex-direction:column;width:116px;transform:translate(-50%,-50%);pointer-events:none;text-align:center}.pie-center small{max-width:110px;overflow:hidden;color:${p=>p.theme.colors.gray};font-size:9px;text-overflow:ellipsis;white-space:nowrap}.pie-center strong{margin-top:4px;font-size:14px;letter-spacing:-.03em}.pie-center em{margin-top:3px;color:#75aaff;font-size:8px;font-style:normal}.chart-tooltip{display:grid;gap:3px;padding:9px 11px;border:1px solid rgba(148,163,184,.25);border-radius:9px;color:#f8fafc;background:#111b2e;box-shadow:0 10px 30px rgba(0,0,0,.3)}.chart-tooltip strong{font-size:11px}.chart-tooltip span{color:#a8b6ca;font-size:10px}
.pie-legend{display:grid;gap:5px;max-height:250px;overflow-y:auto;padding-right:3px}.pie-empty{display:flex;align-items:center;justify-content:center;flex-direction:column;min-height:245px;color:${p=>p.theme.colors.gray};text-align:center}.pie-empty strong{color:${p=>p.theme.colors.white};font-size:14px}.pie-empty span{margin-top:5px;font-size:10px}
@media(max-width:1100px){.pie-content{grid-template-columns:1fr}.chart-wrap{height:230px}.pie-legend{max-height:none}}@media(max-width:700px){padding:16px;.pie-header{margin-bottom:8px}.pie-content{gap:8px}.chart-wrap{height:225px}.pie-legend{grid-template-columns:repeat(2,minmax(0,1fr));gap:6px}}@media(max-width:430px){.pie-legend{grid-template-columns:1fr}.chart-wrap{height:215px}}`;
export const LegendItem=styled.button<{color:string}>`
position:relative;display:grid;grid-template-columns:8px minmax(0,1fr) auto;align-items:center;gap:8px;width:100%;padding:8px 9px 11px;border:1px solid transparent;border-radius:9px;color:inherit;background:rgba(15,23,42,.18);font:inherit;text-align:left;cursor:${p=>p.disabled?'default':'pointer'};&:not(:disabled):hover{border-color:${p=>p.color}66;background:${p=>p.color}10}>i{width:8px;height:8px;border-radius:3px;background:${p=>p.color};box-shadow:0 0 0 3px ${p=>p.color}1c}>span{display:grid;gap:2px;min-width:0}>span strong{overflow:hidden;font-size:10px;text-overflow:ellipsis;white-space:nowrap}>span small{color:${p=>p.theme.colors.gray};font-size:9px}>b{color:${p=>p.color};font-size:10px}>em{position:absolute;right:9px;bottom:5px;left:25px;height:2px;overflow:hidden;border-radius:99px;background:rgba(148,163,184,.12)}>em>i{display:block;height:100%;border-radius:99px;background:${p=>p.color}}`;
