import styled from 'styled-components';
export const Container = styled.div`
  max-width:980px;margin:18px auto 48px;min-width:0;header{max-width:660px;margin-bottom:28px}header>span{display:flex;align-items:center;gap:6px;color:#68a9ff;font-size:10px;font-weight:800;letter-spacing:.13em}h1{margin:8px 0 10px;color:${p=>p.theme.colors.white};font-size:clamp(26px,4vw,38px);letter-spacing:-.04em}header p{color:${p=>p.theme.colors.gray};font-size:14px;line-height:1.6}main{display:grid;grid-template-columns:1fr 1fr;gap:16px}.setting-card{position:relative;display:grid;grid-template-columns:46px minmax(0,1fr) 24px;gap:15px;align-items:start;min-width:0;min-height:180px;padding:22px;border:1px solid ${p=>p.theme.colors.tertiary};border-radius:16px;color:inherit;background:${p=>p.theme.colors.secondary};text-decoration:none;transition:transform .18s,border-color .18s,box-shadow .18s}.setting-card:hover{transform:translateY(-3px);border-color:#397fc2;box-shadow:0 14px 30px rgba(0,0,0,.16)}.icon{display:grid;place-items:center;width:46px;height:46px;border-radius:12px;color:#9ccaff;background:rgba(57,127,194,.16);font-size:24px}.budget .icon{color:#ffd166;background:rgba(255,209,102,.12)}.recurring .icon{color:#68e1b1;background:rgba(91,224,173,.13)}.memory .icon{color:#b6a5ff;background:rgba(130,107,255,.14)}small{color:${p=>p.theme.colors.gray};font-size:10px;font-weight:800;letter-spacing:.1em}h2{margin:7px 0;color:${p=>p.theme.colors.white};font-size:18px}p{margin:0;color:${p=>p.theme.colors.gray};font-size:13px;line-height:1.55;overflow-wrap:anywhere}.arrow{align-self:center;color:${p=>p.theme.colors.gray};font-size:22px}@media(max-width:650px){&{margin-top:5px}header{margin-bottom:20px}main{grid-template-columns:1fr;gap:12px}.setting-card{min-height:0;padding:16px;grid-template-columns:42px minmax(0,1fr) 20px;gap:12px}.icon{width:42px;height:42px;font-size:21px}}
  .microsoft .icon{color:#8fb5ff;background:rgba(88,125,255,.15)}
  .gmail .icon{color:#65e6b4;background:rgba(70,220,170,.13)}
  .settings-banner{margin-bottom:14px;padding:12px 15px;border:1px solid;border-radius:11px;font-size:12px}.settings-banner.error{color:#ff9eb0;border-color:#6d3145;background:#351725}.settings-banner.success{color:#82dfbb;border-color:#276653;background:#12362e}
  .accounts-heading,.other-heading{display:flex;align-items:end;justify-content:space-between;gap:16px;margin:25px 0 12px}.accounts-heading h2,.other-heading h2{margin:5px 0 0;font-size:20px}.accounts-heading>button{display:flex;align-items:center;gap:6px;padding:9px 12px;border:1px solid #31506e;border-radius:9px;color:#cfe1f5;background:#12263e;font-weight:800}
  .accounts{display:grid;grid-template-columns:1fr 1fr;gap:16px}.account-card{min-width:0;padding:20px;border:1px solid ${p=>p.theme.colors.tertiary};border-radius:16px;background:${p=>p.theme.colors.secondary}.account-head{display:grid;grid-template-columns:46px minmax(0,1fr) auto;align-items:center;gap:13px}.account-head h2{margin:4px 0;font-size:19px}.account-head>b{padding:5px 8px;border-radius:999px;color:#d9b96b;background:#3e331b;font-size:9px;text-transform:uppercase}.account-head>b.connected{color:#74deb8;background:#153a31}.account-head>b.unavailable{color:#ff99ad;background:#3a1b27}.activity-automation{display:flex;align-items:center;gap:12px;margin-top:16px;padding-top:14px;border-top:1px solid #213a55}.activity-automation>span{flex:1;min-width:0}.activity-automation strong{display:block;color:#eef5ff;font-size:12px}.activity-automation small{display:block;margin-top:4px;color:#8196b1;font-size:10px;line-height:1.4;letter-spacing:0}.activity-automation input{width:18px;height:18px;accent-color:#6655e8}.connect-button,.disconnect{margin-top:15px;padding:10px 13px;border:1px solid #6655e8;border-radius:9px;color:#fff;background:#6655e8;font-weight:800}.disconnect{border-color:#5b3543;color:#ff9bad;background:#2d1821}.account-error{margin-top:10px!important;color:#ffc270!important;font-size:11px!important}.other-heading{justify-content:flex-start;margin-top:30px}
  @media(max-width:760px){.accounts{grid-template-columns:1fr}.account-head{grid-template-columns:42px minmax(0,1fr)}.account-head>b{grid-column:2;justify-self:start}.accounts-heading{align-items:flex-start}.accounts-heading>button{flex:none}}
`;
