import React, { useCallback, useEffect, useState } from 'react';
import axios from 'axios';
import { FaWhatsapp } from 'react-icons/fa';
import { URL_API } from '../../repositories/baseAPI';
import { safeImageSource } from '../../utils/safeUrl';

type Status={configured:boolean;connected:boolean;gatewayState:string;qrCode?:string;phoneNumber?:string;displayName?:string;allowSend:boolean;groupsEnabled:boolean;secondBrainEnabled:boolean;readReceiptsEnabled:boolean;lastError?:string};
const messageOf=(error:any,fallback:string)=>error?.response?.data?.message||fallback;

export default function WhatsAppConnectionCard({onNotice,onError}:{onNotice:(value:string)=>void;onError:(value:string)=>void}){
  const [status,setStatus]=useState<Status>(); const [busy,setBusy]=useState('');
  const load=useCallback(async()=>{try{const {data}=await axios.get<Status>(`${URL_API}/whatsapp/connection`);setStatus(data)}catch(error){onError(messageOf(error,'Não foi possível consultar o WhatsApp.'))}},[onError]);
  useEffect(()=>{void load()},[load]);
  useEffect(()=>{if(status?.gatewayState!=='qr'&&status?.gatewayState!=='connecting'&&status?.gatewayState!=='reconnecting')return;const timer=window.setInterval(()=>void load(),2000);return()=>window.clearInterval(timer)},[load,status?.gatewayState]);
  const connect=async()=>{setBusy('connect');onError('');try{await axios.post(`${URL_API}/whatsapp/connection`);onNotice('Pareamento iniciado. Leia o QR Code pelo WhatsApp do celular.');await load()}catch(error){onError(messageOf(error,'Não foi possível iniciar o pareamento.'))}finally{setBusy('')}};
  const disconnect=async()=>{if(!window.confirm('Desconectar o dispositivo vinculado? Será necessário ler um novo QR Code para reconectar.'))return;setBusy('disconnect');try{await axios.delete(`${URL_API}/whatsapp/connection`);onNotice('WhatsApp desconectado e sessão local removida.');await load()}catch(error){onError(messageOf(error,'Não foi possível desconectar o WhatsApp.'))}finally{setBusy('')}};
  const toggle=async(key:keyof Pick<Status,'allowSend'|'groupsEnabled'|'secondBrainEnabled'|'readReceiptsEnabled'>,value:boolean)=>{setBusy(key);try{const {data}=await axios.put<Status>(`${URL_API}/whatsapp/preferences`,{[key]:value});setStatus(current=>({...current!,...data}));onNotice('Preferência do WhatsApp salva.')}catch(error){onError(messageOf(error,'Não foi possível salvar a preferência.'))}finally{setBusy('')}};
  const unavailable=status&&!status.configured;
  return <article className="account-card whatsapp"><div className="account-head"><div className="icon"><FaWhatsapp/></div><div><small>PESSOAL · DISPOSITIVO VINCULADO</small><h2>WhatsApp</h2><p>{status?.connected?(status.displayName||status.phoneNumber||'Conta vinculada'):'Leia as novas mensagens e responda somente após confirmar.'}</p></div><b className={status?.connected?'connected':unavailable?'unavailable':''}>{status?.connected?'Conectado':unavailable?'Indisponível':status?.gatewayState==='qr'?'Aguardando QR':'Desconectado'}</b></div>
    {safeImageSource(status?.qrCode)&&!status?.connected?<div className="whatsapp-qr"><img src={safeImageSource(status?.qrCode)} alt="QR Code para vincular o WhatsApp"/><strong>WhatsApp → Dispositivos conectados → Conectar dispositivo</strong><small>O código muda automaticamente. Mantenha esta tela aberta até concluir.</small></div>:null}
    {status?.connected?<><label className="activity-automation"><span><strong>Permitir envio manual</strong><small>Cada mensagem ainda exige confirmação na conversa.</small></span><input type="checkbox" checked={status.allowSend} disabled={!!busy} onChange={event=>void toggle('allowSend',event.target.checked)}/></label><label className="activity-automation"><span><strong>Incluir no Second Brain</strong><small>Relaciona novas mensagens autorizadas a ideias, projetos e decisões.</small></span><input type="checkbox" checked={status.secondBrainEnabled} disabled={!!busy} onChange={event=>void toggle('secondBrainEnabled',event.target.checked)}/></label><label className="activity-automation"><span><strong>Ler grupos</strong><small>Desligado por padrão para proteger conversas coletivas.</small></span><input type="checkbox" checked={status.groupsEnabled} disabled={!!busy} onChange={event=>void toggle('groupsEnabled',event.target.checked)}/></label><label className="activity-automation"><span><strong>Confirmação de leitura</strong><small>Permite marcar mensagens como lidas pelo dispositivo vinculado.</small></span><input type="checkbox" checked={status.readReceiptsEnabled} disabled={!!busy} onChange={event=>void toggle('readReceiptsEnabled',event.target.checked)}/></label><button className="disconnect" disabled={!!busy} onClick={()=>void disconnect()}>{busy==='disconnect'?'Desconectando…':'Desconectar dispositivo'}</button></>:<button className="connect-button" disabled={!!busy||unavailable} onClick={()=>void connect()}>{busy==='connect'?'Iniciando…':status?.gatewayState==='qr'?'Gerar novo QR Code':'Vincular WhatsApp'}</button>}
    {status?.lastError?<p className="account-error">{status.lastError}</p>:null}{unavailable?<p className="account-error">Configure o segredo e o serviço whatsapp-gateway na API.</p>:null}</article>;
}
