import React,{useCallback,useEffect,useMemo,useState}from'react';
import axios from'axios';
import{MdCheck,MdClose,MdEdit,MdPlayArrow,MdSave}from'react-icons/md';
import{URL_API}from'../../repositories/baseAPI';

type Item=Record<string,any>;
type Props={domains:Item[];onError:(value:string)=>void;onNotice:(value:string)=>void};
const iso=(value?:string)=>value?new Date(value).toLocaleString('pt-BR'):'—';

export default function BackfillPanel({domains,onError,onNotice}:Props){
 const[summary,setSummary]=useState<Item|null>(null),[runs,setRuns]=useState<Item[]>([]),[run,setRun]=useState<Item|null>(null),[candidates,setCandidates]=useState<Item[]>([]),[busy,setBusy]=useState(false);
 const[config,setConfig]=useState({dateFrom:'',dateTo:'',agents:[]as string[],batchSize:25,maxMessages:500});
 const[filters,setFilters]=useState({domainKey:'',memoryType:'',status:''}),[selected,setSelected]=useState<number[]>([]),[editing,setEditing]=useState<Item|null>(null),[confirmCommit,setConfirmCommit]=useState(false);
 const message=(error:any,fallback:string)=>error.response?.data?.message||fallback;
 const loadBase=useCallback(async()=>{try{const[s,r]=await Promise.all([axios.get(`${URL_API}/api/ai/memory-backfill/source-summary`),axios.get(`${URL_API}/api/ai/memory-backfill/runs`)]);setSummary(s.data);setRuns(r.data.runs||[]);setConfig(value=>({...value,batchSize:s.data.limits?.batchSize||value.batchSize,maxMessages:s.data.limits?.maxMessages||value.maxMessages}))}catch(error:any){onError(message(error,'Não foi possível carregar o histórico disponível.'))}},[onError]);
 const loadRun=useCallback(async(id:number)=>{const[r,c]=await Promise.all([axios.get(`${URL_API}/api/ai/memory-backfill/runs/${id}`),axios.get(`${URL_API}/api/ai/memory-backfill/runs/${id}/candidates`)]);setRun(r.data);setCandidates(c.data.candidates||[]);setSelected([])},[]);
 useEffect(()=>{void loadBase()},[loadBase]);
 const execute=async(action:()=>Promise<any>,success:string)=>{setBusy(true);onError('');try{const response=await action();const next=response.data.run||response.data;if(next?.id)await loadRun(next.id);await loadBase();onNotice(success)}catch(error:any){onError(message(error,'Não foi possível concluir a operação.'))}finally{setBusy(false)}};
 const preview=()=>execute(()=>axios.post(`${URL_API}/api/ai/memory-backfill/preview`,config),'Prévia criada. Nenhuma memória foi gravada.');
 const process=()=>run&&execute(()=>axios.post(`${URL_API}/api/ai/memory-backfill/runs/${run.id}/process`),'Lote analisado. Revise os candidatos.');
 const cancel=()=>run&&execute(()=>axios.post(`${URL_API}/api/ai/memory-backfill/runs/${run.id}/cancel`),'Execução cancelada.');
 const resume=()=>run&&execute(()=>axios.post(`${URL_API}/api/ai/memory-backfill/runs/${run.id}/resume`),'Execução retomada.');
 const visible=useMemo(()=>candidates.filter(item=>(!filters.domainKey||item.domainKey===filters.domainKey)&&(!filters.memoryType||item.memoryType===filters.memoryType)&&(!filters.status||item.status===filters.status)),[candidates,filters]);
 const toggle=(id:number)=>setSelected(value=>value.includes(id)?value.filter(item=>item!==id):[...value,id]);
 const approveSelected=()=>run&&selected.length&&execute(()=>axios.post(`${URL_API}/api/ai/memory-backfill/runs/${run.id}/approve`,{candidateIds:selected}),'Candidatos selecionados aprovados.');
 const reject=async(item:Item)=>{await execute(()=>axios.post(`${URL_API}/api/ai/memory-backfill/candidates/${item.id}/reject`,{reason:'Rejeitado na revisão humana.'}),'Candidato rejeitado.');};
 const approve=async(item:Item)=>{await execute(()=>axios.post(`${URL_API}/api/ai/memory-backfill/candidates/${item.id}/approve`),'Candidato aprovado.');};
 const saveEdit=async()=>{if(!editing)return;const payload={...editing,tags:Array.isArray(editing.tags)?editing.tags:String(editing.tags||'').split(',').map((value:string)=>value.trim()).filter(Boolean)};await execute(()=>axios.put(`${URL_API}/api/ai/memory-backfill/candidates/${editing.id}`,payload),'Candidato atualizado e reavaliado.');setEditing(null)};
 const commit=async()=>{if(!run)return;setConfirmCommit(false);await execute(()=>axios.post(`${URL_API}/api/ai/memory-backfill/runs/${run.id}/commit`),'Memórias aprovadas foram gravadas.');};
 const approved=candidates.filter(item=>item.status==='approved').length,duplicates=candidates.filter(item=>item.status==='duplicate').length,contradictions=candidates.filter(item=>item.isContradiction).length;
 return <div className="backfill">
  <section className="panel backfill-config"><div><span className="eyebrow">BACKFILL CONTROLADO</span><h2>Selecionar histórico</h2><p className="support">Somente mensagens do usuário são fonte. A prévia cria candidatos para revisão e não grava memórias.</p></div>
   {summary&&!summary.enabled&&<div className="notice error">A funcionalidade está desabilitada por <b>AI_MEMORY_BACKFILL_ENABLED</b>.</div>}
   <div className="metric-row"><Metric label="Mensagens disponíveis" value={summary?.availableMessages??'—'}/><Metric label="Primeira mensagem" value={iso(summary?.firstMessageAt)}/><Metric label="Última mensagem" value={iso(summary?.lastMessageAt)}/></div>
   <div className="grid"><Field label="De" type="date" value={config.dateFrom} onChange={value=>setConfig({...config,dateFrom:value})}/><Field label="Até" type="date" value={config.dateTo} onChange={value=>setConfig({...config,dateTo:value})}/><Field label="Tamanho do lote" type="number" value={config.batchSize} onChange={value=>setConfig({...config,batchSize:Number(value)})}/><Field label="Limite de mensagens" type="number" value={config.maxMessages} onChange={value=>setConfig({...config,maxMessages:Number(value)})}/></div>
   <div className="agent-picker">{(summary?.agents||[]).map((agent:Item)=><label key={agent.agentCode}><input type="checkbox" checked={config.agents.includes(agent.agentCode)} onChange={()=>setConfig({...config,agents:config.agents.includes(agent.agentCode)?config.agents.filter(value=>value!==agent.agentCode):[...config.agents,agent.agentCode]})}/><span>{agent.agentCode||'general'} <small>{agent.messageCount}</small></span></label>)}</div>
   <div className="actions"><button className="primary" disabled={busy||!summary?.enabled||!summary?.availableMessages} onClick={preview}><MdPlayArrow/> Gerar prévia</button></div>
  </section>
  <section className="panel"><h2>Execuções</h2><div className="run-list">{runs.map(item=><button key={item.id} className={run?.id===item.id?'active':''} onClick={()=>loadRun(item.id)}><b>#{item.id}</b><span>{item.status}</span><small>{item.processedMessages}/{item.totalMessages} mensagens · {item.candidateCount} candidatos</small></button>)}{!runs.length&&<div className="empty">Nenhuma execução criada.</div>}</div></section>
  {run&&<><section className="panel run-summary"><header><div><span className="eyebrow">EXECUÇÃO #{run.id}</span><h2>Extração e revisão</h2></div><span className={`status ${run.status}`}>{run.status}</span></header>
   <div className="progress"><i style={{width:`${run.totalMessages?Math.min(100,run.processedMessages/run.totalMessages*100):100}%`}}/></div>
   <div className="metric-row"><Metric label="Analisadas" value={`${run.processedMessages}/${run.totalMessages}`}/><Metric label="Candidatos" value={candidates.length}/><Metric label="Aprovados" value={approved}/><Metric label="Rejeitados" value={candidates.filter(i=>i.status==='rejected').length}/><Metric label="Duplicados" value={duplicates}/><Metric label="Contradições" value={contradictions}/><Metric label="Tokens estimados" value={(run.inputTokens||0)+(run.outputTokens||0)}/><Metric label="Modelo" value={run.model||'—'}/></div>
   {run.errorSummary&&<div className="notice error">{run.errorSummary}</div>}<div className="actions">{run.status==='pending'&&<button className="primary" disabled={busy} onClick={process}>Processar próximo lote</button>}{run.status==='failed'&&<button className="primary" disabled={busy} onClick={resume}>Retomar</button>}{!['completed','cancelled'].includes(run.status)&&<button className="small muted danger" disabled={busy} onClick={cancel}>Cancelar</button>}</div>
  </section>
  <section className="panel candidates"><div className="candidate-head"><h2>Candidatos</h2><div className="toolbar"><select value={filters.domainKey} onChange={e=>setFilters({...filters,domainKey:e.target.value})}><option value="">Todos os domínios</option>{domains.map(d=><option key={d.domainKey}>{d.domainKey}</option>)}</select><select value={filters.memoryType} onChange={e=>setFilters({...filters,memoryType:e.target.value})}><option value="">Todos os tipos</option>{['fact','preference','decision','event','project_state','relationship','constraint','goal','insight'].map(v=><option key={v}>{v}</option>)}</select><select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">Todos os estados</option>{['pending','approved','rejected','committed','duplicate','superseded','error'].map(v=><option key={v}>{v}</option>)}</select></div></div>
   <div className="selection-actions"><label><input type="checkbox" checked={Boolean(visible.length)&&visible.filter(i=>!['duplicate','committed','error'].includes(i.status)).every(i=>selected.includes(i.id))} onChange={e=>setSelected(e.target.checked?visible.filter(i=>!['duplicate','committed','error'].includes(i.status)).map(i=>i.id):[])}/> Selecionar revisáveis</label><button className="small" disabled={!selected.length||busy} onClick={approveSelected}><MdCheck/> Aprovar selecionadas</button></div>
   <div className="candidate-list">{visible.map(item=><article className={`candidate ${item.isContradiction?'contradiction':''}`} key={item.id}><label className="candidate-check"><input type="checkbox" disabled={['duplicate','committed','error'].includes(item.status)} checked={selected.includes(item.id)} onChange={()=>toggle(item.id)}/></label><div><header><h3>{item.subject}</h3><div className="badges"><span className="badge">{item.memoryType}</span><span className="badge">{item.domainKey||'geral'}</span><span className={`badge ${item.status==='rejected'||item.status==='duplicate'?'off':''}`}>{item.status}</span>{item.isContradiction&&<span className="badge warning">possível contradição · desativa #{item.supersedesMemoryId}</span>}{item.duplicateMemoryId&&<span className="badge off">duplicada de #{item.duplicateMemoryId}</span>}</div></header><p>{item.content}</p>{item.duplicateMemory&&<div className="comparison"><b>Memória existente #{item.duplicateMemory.id}</b><span>{item.duplicateMemory.content}</span></div>}{item.supersededMemory&&<div className="comparison warning"><b>Possível informação anterior #{item.supersededMemory.id}</b><span>{item.supersededMemory.content}</span></div>}<div className="meta"><span>Importância {Number(item.importance).toFixed(2)}</span><span>Confiança {Number(item.confidence).toFixed(2)}</span><span>Origem {(item.sourceMessageIds||[]).join(', ')}</span><span>{item.extractionReason}</span></div><div className="actions"><button className="small muted" onClick={()=>setEditing({...item,tags:(item.tags||[]).join(', ')})}><MdEdit/> Editar</button>{!['duplicate','committed','error'].includes(item.status)&&<button className="small" onClick={()=>approve(item)}><MdCheck/> Aprovar</button>}{item.status!=='committed'&&<button className="small muted danger" onClick={()=>reject(item)}><MdClose/> Rejeitar</button>}</div></div></article>)}{!visible.length&&<div className="empty">Nenhum candidato neste filtro.</div>}</div>
  </section>
  {editing&&<section className="panel edit-candidate"><h2>Editar antes de aprovar</h2><div className="grid"><Field label="Assunto" value={editing.subject} onChange={value=>setEditing({...editing,subject:value})}/><label className="field"><span>Domínio</span><select value={editing.domainKey||''} onChange={e=>setEditing({...editing,domainKey:e.target.value})}><option value="">Geral</option>{domains.map(d=><option key={d.domainKey}>{d.domainKey}</option>)}</select></label></div><label className="field"><span>Conteúdo</span><textarea value={editing.content} onChange={e=>setEditing({...editing,content:e.target.value})}/></label><div className="grid"><Field label="Importância" type="number" value={editing.importance} onChange={value=>setEditing({...editing,importance:Number(value)})}/><Field label="Confiança" type="number" value={editing.confidence} onChange={value=>setEditing({...editing,confidence:Number(value)})}/><Field label="Tags" value={editing.tags} onChange={value=>setEditing({...editing,tags:value})}/></div><div className="actions"><button className="small muted" onClick={()=>setEditing(null)}>Cancelar</button><button className="primary" onClick={saveEdit}><MdSave/> Salvar edição</button></div></section>}
  {run.status==='review'&&<section className="panel commit"><h2>Gravar memórias aprovadas</h2><div className="metric-row"><Metric label="Serão criadas" value={approved}/><Metric label="Serão desativadas" value={candidates.filter(i=>i.status==='approved'&&i.supersedesMemoryId).length}/><Metric label="Duplicadas ignoradas" value={duplicates}/><Metric label="Custo" value="dependente do provider"/></div>{!confirmCommit?<button className="primary" disabled={!approved||busy} onClick={()=>setConfirmCommit(true)}>Revisar gravação final</button>:<div className="commit-confirm"><p>Esta ação cria somente os candidatos aprovados. Contradições aprovadas desativarão a memória anterior, preservando o histórico.</p><div className="actions"><button className="small muted" onClick={()=>setConfirmCommit(false)}>Voltar</button><button className="primary" onClick={commit}>Gravar {approved} memórias aprovadas</button></div></div>}</section>}
  </>}
 </div>
}

const Metric=({label,value}:{label:string;value:any})=><div className="metric"><span>{label}</span><b>{value}</b></div>;
const Field=({label,value,onChange,type='text'}:{label:string;value:any;onChange:(value:string)=>void;type?:string})=><label className="field"><span>{label}</span><input type={type} value={value??''} min={type==='number'?1:undefined} onChange={event=>onChange(event.target.value)}/></label>;
