import React,{useCallback,useEffect,useMemo,useState}from'react';
import axios from'axios';
import{MdAdd,MdBugReport,MdMemory,MdRefresh}from'react-icons/md';
import{URL_API}from'../../repositories/baseAPI';
import{Container}from'./styles';
import BackfillPanel from'./BackfillPanel';
import {Link} from 'react-router-dom';

type Tab='memories'|'backfill'|'contexts'|'agents'|'debug';
type AnyItem=Record<string,any>;
const emptyMemory={memoryType:'fact',domainKey:'',subject:'',content:'',importance:.7,confidence:1,tags:[],isActive:true};
const emptyDomain={domainKey:'',title:'',description:'',content:'',priority:50,isActive:true};
const emptyAgent={agentKey:'',name:'',description:'',systemInstructions:'',defaultModel:'gpt-5.6',temperature:.2,isActive:true,contexts:[]};
const iso=(value?:string)=>value?new Date(value).toLocaleString('pt-BR'):'—';

export default function AIContext(){
 const[tab,setTab]=useState<Tab>('memories'),[profiles,setProfiles]=useState<AnyItem[]>([]),[domains,setDomains]=useState<AnyItem[]>([]),[memories,setMemories]=useState<AnyItem[]>([]),[agents,setAgents]=useState<AnyItem[]>([]);
 const[selected,setSelected]=useState<AnyItem|null>(null),[form,setForm]=useState<AnyItem>(emptyMemory),[query,setQuery]=useState(''),[domainFilter,setDomainFilter]=useState(''),[typeFilter,setTypeFilter]=useState(''),[activeFilter,setActiveFilter]=useState('true'),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const[debugForm,setDebugForm]=useState({agent_key:'general',message:''}),[preview,setPreview]=useState<AnyItem|null>(null),[loading,setLoading]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const[p,d,m,a]=await Promise.all([axios.get(`${URL_API}/api/ai/context/profile`,{params:{includeInactive:true}}),axios.get(`${URL_API}/api/ai/context/domains`,{params:{includeInactive:true}}),axios.get(`${URL_API}/api/ai/memories`,{params:{active:activeFilter===''?undefined:activeFilter}}),axios.get(`${URL_API}/api/ai/agents`,{params:{includeInactive:true}})]);setProfiles(p.data.profiles||[]);setDomains(d.data.domains||[]);setMemories(m.data.memories||[]);setAgents(a.data.agents||[])}catch(e:any){setError(e.response?.data?.message||'Não foi possível carregar o módulo de contexto. A migration pode ainda não ter sido aplicada.')}finally{setLoading(false)}},[activeFilter]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{setSelected(null);setForm(tab==='memories'?emptyMemory:tab==='contexts'?emptyDomain:emptyAgent)},[tab]);
 const visible=useMemo(()=>memories.filter(item=>(!query||`${item.subject} ${item.content} ${(item.tags||[]).join(' ')}`.toLowerCase().includes(query.toLowerCase()))&&(!domainFilter||item.domainKey===domainFilter)&&(!typeFilter||item.memoryType===typeFilter)),[memories,query,domainFilter,typeFilter]);
 const edit=(item:AnyItem)=>{setSelected(item);setForm({...item,tags:item.tags||[],contexts:item.contexts||[]})};
 const saveMemory=async()=>{const body={...form,tags:Array.isArray(form.tags)?form.tags:String(form.tags||'').split(',').map((v:string)=>v.trim()).filter(Boolean)};selected?await axios.put(`${URL_API}/api/ai/memories/${selected.id}`,body):await axios.post(`${URL_API}/api/ai/memories`,body)};
 const saveContext=async()=>{if(form.contextKey){await axios.put(`${URL_API}/api/ai/context/profile`,form)}else{const key=selected?.domainKey||form.domainKey;key?await axios.put(`${URL_API}/api/ai/context/domains/${encodeURIComponent(key)}`,form):await axios.post(`${URL_API}/api/ai/context/domains`,form)}};
 const saveAgent=async()=>{selected?await axios.put(`${URL_API}/api/ai/agents/${selected.id}`,form):await axios.post(`${URL_API}/api/ai/agents`,form)};
 const save=async()=>{try{tab==='memories'?await saveMemory():tab==='contexts'?await saveContext():await saveAgent();setNotice('Alteração salva.');setSelected(null);setForm(tab==='memories'?emptyMemory:tab==='contexts'?emptyDomain:emptyAgent);await load()}catch(e:any){setError(e.response?.data?.message||'Não foi possível salvar.')}};
 const deactivate=async(item:AnyItem,kind:Tab)=>{try{const url=kind==='memories'?`/api/ai/memories/${item.id}`:kind==='contexts'?`/api/ai/context/domains/${item.domainKey}`:`/api/ai/agents/${item.id}`;await axios.delete(`${URL_API}${url}`);await load()}catch(e:any){setError(e.response?.data?.message||'Não foi possível desativar.')}};
 const hardDeleteMemory=async(item:AnyItem)=>{if(!window.confirm('Excluir definitivamente esta memória?'))return;try{await axios.delete(`${URL_API}/api/ai/memories/${item.id}`,{params:{hard:true}});await load()}catch(e:any){setError(e.response?.data?.message||'Não foi possível excluir.')}};
 const runPreview=async()=>{try{setPreview((await axios.post(`${URL_API}/api/ai/context/preview`,debugForm)).data)}catch(e:any){setError(e.response?.data?.message||'Não foi possível montar a prévia.')}};
 const set=(key:string,value:any)=>setForm(current=>({...current,[key]:value}));
 return <Container><header className="heading"><div><span>CONHECIMENTO PESSOAL E AUDITÁVEL</span><h1>Memória conectada</h1><p>Gerencie as memórias e os contextos dos agentes. O mapa agora está no módulo Segundo cérebro.</p></div><button className="refresh" onClick={load}><MdRefresh/> {loading?'Carregando':'Atualizar dados'}</button></header>
 <nav className="tabs">{([['memories','Memórias'],['backfill','Importar histórico'],['contexts','Contextos'],['agents','Agentes'],['debug','Diagnóstico']]as[Tab,string][]).map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{key==='debug'?<MdBugReport/>:key==='memories'||key==='backfill'?<MdMemory/>:null} {label}</button>)}</nav>
 {notice&&<div className="notice">{notice}</div>}{error&&<div className="notice error">{error}</div>}
 {tab==='backfill'&&<BackfillPanel domains={domains} onError={setError} onNotice={setNotice}/>}
<p><Link to="/second-brain">Abrir Segundo cérebro →</Link></p>
 {tab==='memories'&&<><div className="toolbar"><input placeholder="Buscar assunto, conteúdo ou tag" value={query} onChange={e=>setQuery(e.target.value)}/><select value={domainFilter} onChange={e=>setDomainFilter(e.target.value)}><option value="">Todos os domínios</option>{domains.map(d=><option key={d.domainKey}>{d.domainKey}</option>)}</select><select value={typeFilter} onChange={e=>setTypeFilter(e.target.value)}><option value="">Todos os tipos</option>{['fact','preference','decision','event','project_state','relationship','constraint','goal','insight'].map(v=><option key={v}>{v}</option>)}</select><select value={activeFilter} onChange={e=>setActiveFilter(e.target.value)}><option value="true">Ativas</option><option value="false">Inativas</option><option value="">Todas</option></select><button className="small" onClick={()=>{setSelected(null);setForm(emptyMemory)}}><MdAdd/> Nova</button></div><div className="layout"><section className="panel"><h2>{visible.length} memórias</h2><div className="list">{visible.map(item=><article className="card" key={item.id}><header><h3>{item.subject}</h3><div className="badges"><span className="badge">{item.memoryType}</span><span className="badge">{item.domainKey||'geral'}</span>{!item.isActive&&<span className="badge off">inativa</span>}</div></header><p>{item.content}</p><div className="meta"><span>Importância {Number(item.importance).toFixed(2)}</span><span>Confiança {Number(item.confidence).toFixed(2)}</span><span>Evento {iso(item.eventDate)}</span><span>Criada {iso(item.createdAt)}</span><span>Último uso {iso(item.lastUsedAt)}</span><span>Usos {item.useCount||0}</span></div><div className="badges">{(item.tags||[]).map((t:string)=><span className="badge" key={t}>#{t}</span>)}</div><div className="actions"><button className="small muted" onClick={()=>edit(item)}>Editar</button>{item.isActive&&<button className="small muted danger" onClick={()=>deactivate(item,'memories')}>Desativar</button>}<button className="small muted danger" onClick={()=>hardDeleteMemory(item)}>Excluir</button></div></article>)}{!visible.length&&<div className="empty">Nenhuma memória encontrada.</div>}</div></section><Editor title={selected?'Editar memória':'Nova memória'} form={form} set={set} kind="memory" domains={domains} onSave={save}/></div></>}
 {tab==='contexts'&&<div className="layout"><section className="panel"><h2>Core Profile e domínios</h2><div className="list">{[...profiles,...domains].map(item=><article className="card" key={item.contextKey||item.domainKey}><header><h3>{item.title}</h3><div className="badges"><span className="badge">{item.contextKey?'profile':item.domainKey}</span>{item.alwaysInclude&&<span className="badge">always include</span>}{!item.isActive&&<span className="badge off">inativo</span>}</div></header><p>{item.content}</p><div className="meta"><span>Prioridade {item.priority}</span><span>Versão {item.version}</span><span>Atualizado {iso(item.updatedAt)}</span></div><div className="actions"><button className="small muted" onClick={()=>edit(item)}>Editar</button>{item.domainKey&&item.isActive&&<button className="small muted danger" onClick={()=>deactivate(item,'contexts')}>Desativar</button>}</div></article>)}</div></section><Editor title={selected?'Editar contexto':'Novo domínio'} form={form} set={set} kind="context" domains={domains} onSave={save}/></div>}
 {tab==='agents'&&<div className="layout"><section className="panel"><h2>Agentes configuráveis</h2><div className="list">{agents.map(item=><article className="card" key={item.id}><header><h3>{item.name}</h3><div className="badges"><span className="badge">{item.agentKey}</span>{!item.isActive&&<span className="badge off">inativo</span>}</div></header><p>{item.description}</p><div className="badges">{(item.contexts||[]).map((c:AnyItem)=><span className="badge" key={c.domainKey}>{c.domainKey}{c.alwaysInclude?' · always':''}</span>)}</div><div className="meta"><span>Modelo {item.defaultModel||'padrão'}</span><span>Temperatura {item.temperature}</span><span>Atualizado {iso(item.updatedAt)}</span></div><div className="actions"><button className="small muted" onClick={()=>edit(item)}>Editar</button>{item.isActive&&<button className="small muted danger" onClick={()=>deactivate(item,'agents')}>Desativar</button>}</div></article>)}</div></section><Editor title={selected?'Editar agente':'Novo agente'} form={form} set={set} kind="agent" domains={domains} onSave={save}/></div>}
 {tab==='debug'&&<div className="debug"><section className="panel form"><h2>Simular requisição</h2><label className="field"><span>Agente</span><select value={debugForm.agent_key} onChange={e=>setDebugForm({...debugForm,agent_key:e.target.value})}>{agents.map(a=><option key={a.agentKey}>{a.agentKey}</option>)}{!agents.length&&<option>general</option>}</select></label><label className="field"><span>Mensagem</span><textarea value={debugForm.message} onChange={e=>setDebugForm({...debugForm,message:e.target.value})} placeholder="Quero alterar o deploy do servidor"/></label><button className="primary" onClick={runPreview}>Montar contexto</button></section><section className="panel"><h2>Contexto final</h2>{preview?<><div className="badges">{(preview.selected_domains||[]).map((d:AnyItem)=><span className="badge" key={d.key}>{d.key} · {d.score}</span>)}<span className="badge">{preview.estimated_tokens} tokens estimados</span><span className="badge">{(preview.memories||[]).length} memórias</span></div><pre>{preview.final_context}</pre></>:<div className="empty">Informe uma mensagem para inspecionar router, domínios, memórias e orçamento.</div>}</section></div>}
 </Container>
}

function Editor({title,form,set,kind,domains,onSave}:{title:string;form:AnyItem;set:(k:string,v:any)=>void;kind:'memory'|'context'|'agent';domains:AnyItem[];onSave:()=>void}){
 return <aside className="panel form"><h2>{title}</h2>{kind==='memory'&&<><div className="grid"><label className="field"><span>Tipo</span><select value={form.memoryType||''} onChange={e=>set('memoryType',e.target.value)}>{['fact','preference','decision','event','project_state','relationship','constraint','goal','insight'].map(v=><option key={v}>{v}</option>)}</select></label><label className="field"><span>Domínio</span><select value={form.domainKey||''} onChange={e=>set('domainKey',e.target.value)}><option value="">Geral</option>{domains.map(d=><option key={d.domainKey}>{d.domainKey}</option>)}</select></label></div><Field label="Subject" value={form.subject} onChange={v=>set('subject',v)}/><Area label="Content" value={form.content} onChange={v=>set('content',v)}/><div className="grid"><Field label="Importância 0–1" type="number" value={form.importance} onChange={v=>set('importance',Number(v))}/><Field label="Confiança 0–1" type="number" value={form.confidence} onChange={v=>set('confidence',Number(v))}/></div><Field label="Tags separadas por vírgula" value={Array.isArray(form.tags)?form.tags.join(', '):form.tags} onChange={v=>set('tags',v)}/></>}
 {kind==='context'&&<><Field label={form.contextKey?'Context key':'Domain key'} value={form.contextKey||form.domainKey||''} disabled={Boolean(form.contextKey||form.id)} onChange={v=>set('domainKey',v)}/><Field label="Título" value={form.title} onChange={v=>set('title',v)}/>{!form.contextKey&&<Field label="Descrição" value={form.description} onChange={v=>set('description',v)}/>}<Area label="Conteúdo" value={form.content} onChange={v=>set('content',v)}/><Field label="Prioridade" type="number" value={form.priority} onChange={v=>set('priority',Number(v))}/>{form.contextKey&&<label className="checks"><input type="checkbox" checked={Boolean(form.alwaysInclude)} onChange={e=>set('alwaysInclude',e.target.checked)}/> Always include</label>}</>}
 {kind==='agent'&&<><Field label="Agent key" value={form.agentKey} disabled={Boolean(form.id)} onChange={v=>set('agentKey',v)}/><Field label="Nome" value={form.name} onChange={v=>set('name',v)}/><Field label="Descrição" value={form.description} onChange={v=>set('description',v)}/><Area label="System instructions" value={form.systemInstructions} onChange={v=>set('systemInstructions',v)}/><div className="grid"><Field label="Modelo" value={form.defaultModel} onChange={v=>set('defaultModel',v)}/><Field label="Temperatura" type="number" value={form.temperature} onChange={v=>set('temperature',Number(v))}/></div><label className="field"><span>Domínios associados</span><select multiple value={(form.contexts||[]).map((c:AnyItem)=>c.domainKey)} onChange={e=>set('contexts',Array.from(e.target.selectedOptions).map(o=>({domainKey:o.value,priority:80,alwaysInclude:false})))}>{domains.map(d=><option key={d.domainKey}>{d.domainKey}</option>)}</select></label><div className="context-config">{(form.contexts||[]).map((context:AnyItem,index:number)=><label key={context.domainKey}><b>{context.domainKey}</b><span>Prioridade <input type="number" min="0" max="100" value={context.priority??80} onChange={e=>set('contexts',(form.contexts||[]).map((item:AnyItem,i:number)=>i===index?{...item,priority:Number(e.target.value)}:item))}/></span><span><input type="checkbox" checked={Boolean(context.alwaysInclude)} onChange={e=>set('contexts',(form.contexts||[]).map((item:AnyItem,i:number)=>i===index?{...item,alwaysInclude:e.target.checked}:item))}/> always</span></label>)}</div></>}
 <div className="form-actions"><button className="primary" onClick={onSave}>Salvar</button></div></aside>
}
const Field=({label,value,onChange,type='text',disabled=false}:{label:string;value:any;onChange:(v:string)=>void;type?:string;disabled?:boolean})=><label className="field"><span>{label}</span><input type={type} disabled={disabled} value={value??''} min={type==='number'?0:undefined} step={type==='number'?0.05:undefined} onChange={e=>onChange(e.target.value)}/></label>;
const Area=({label,value,onChange}:{label:string;value:any;onChange:(v:string)=>void})=><label className="field"><span>{label}</span><textarea value={value??''} onChange={e=>onChange(e.target.value)}/></label>;
